### ISSUE TITLE
Remove demo behavior

### ISSUE THREAD

**Issue by lgarciatEveris** [transistorsoft/nativescript-background-geolocation-lt#103]
## Your Environment
* Plugin version: 1.80
* Platform: iOS and Android
* OS version: All
* Device manufacturer / model: Emulators and devices
* Nativescript version (`tns info`): 
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 3.4.2           │ 3.4.2          │ Up to date    │
│ tns-core-modules │ 3.4.0           │ 3.4.0          │ Up to date    │
│ tns-android      │                 │ 3.4.1          │ Not installed │
│ tns-ios          │ 3.4.1           │ 3.4.1          │ Up to date    │
└──────────────────┴─────────────────┴────────────────┴───────────────┘

* Plugin config

## Expected Behavior

  I have create a brand new project and install nativescript-background-geolocation-lt. Its working fine in IOS and android, but some behaviors of demo application does not disappear, as notifications(in demo pattern), sounds when notify. How can i disable it?

## Actual Behavior

The events that i set(how onMotionChange or onLocation) is working, but the demo events are being triggered too.
<img width="291" alt="captura de tela 2018-02-15 as 12 07 15" src="https://user-images.githubusercontent.com/33911280/36270046-cc402354-1248-11e8-9573-7eb4bbe73eaf.png">
## Steps to Reproduce

1. tns create testGeo_pure
2. cd testGeo_pure/  
3. tns plugin add nativescript-background-geolocation-lt
4. Put the code in the main page:
`import {Observable} from 'data/observable';
import Platform = require('platform');
import * as dialogs from "ui/dialogs";
import {BackgroundGeolocation} from "nativescript-background-geolocation-lt";
import {BackgroundFetch} from "nativescript-background-fetch";
import * as LocalNotifications from "nativescript-local-notifications";
import * as Toast from 'nativescript-toast';
import { Border } from "tns-core-modules/ui/border";
import frames = require("ui/frame");

class createViewModel extends Observable{
    private _state: any;
    private images: Array<object> = [];
    constructor() {
      super();
      LocalNotifications.hasPermission();
      // 1. Listen to events
      BackgroundGeolocation.on("location", this.onLocation.bind(this));
      BackgroundGeolocation.on("motionchange", this.onMotionChange.bind(this));
       BackgroundGeolocation.on("http", null);
       BackgroundGeolocation.on("heartbeat", null);
       BackgroundGeolocation.on("schedule", null);
       BackgroundGeolocation.on("error", null);
  
      // 2. Configure it.
      BackgroundGeolocation.configure({
        debug: true,
        desiredAccuracy: 0,
        stationaryRadius: 25,
        distanceFilter: 100,
        activityRecognitionInterval: 10000,
        autoSync: true
      }, (state) => {
        // 3. Plugin is now ready to use.
        if (!state.enabled) {
          BackgroundGeolocation.start();
        }
      });
}
private onLocation(location:any) {
    console.log('[event] location: ', location);
    this.set("message",JSON.stringify(location, null, 2));
    console.log("location" + location.coords.latitude);
    console.log("odometer" + location.odometer);
    BackgroundGeolocation.logger.notice('Location received in client');

    LocalNotifications.schedule([{
      id: 1,
      title: 'onLocation',
      body: "location: " + location.coords.latitude,
      ticker: 'The ticker',
      badge: 1,

      ongoing: false, 
      interval: 'second',
      at: new Date(new Date().getTime() + (10 * 10)) // 10 seconds from now
    }]).then(
        function() {
          console.log("Notification scheduled");
        },
        function(error) {
          console.log("scheduling error: " + error);
        }
    )
  }

  private onMotionChange(isMoving:boolean, location:any) {
    console.log('[event] motionchange: ', isMoving, location);

    LocalNotifications.schedule([{
      id: 1,
      title: 'onMotionChange',
      body: "location: " + location.coords.latitude,
      ticker: 'The ticker',
      badge: 1,

      ongoing: false, // makes the notification ongoing (Android only)
      interval: 'second',
 
      at: new Date(new Date().getTime() + (10 * 10)) // 10 seconds from now
    }]).then(
        function() {
          console.log("Notification scheduled");
        },
        function(error) {
          console.log("scheduling error: " + error);
        }
    )
  }
 private onTap(){
  BackgroundGeolocation.getCurrentPosition(function (location:any){
    this.set("message",JSON.stringify(location, null, 2));
  });
    //this.set("message", "asd");
 }
}
export default createViewModel;
//exports.createViewModel = createViewModel;`

## Context

I trying to create a application with no demo dehaviors

**Comment by christocracy** [comment]
It's called [Debug mode](https://github.com/transistorsoft/nativescript-background-geolocation-lt/tree/master/docs#config-boolean-debug-false)

`{debug: false}`.

These messages / sound Fx are there to assist you during development.
