### ISSUE TITLE
Updating app deletes / clears all location data

### ISSUE THREAD

**Issue by 3rror404** [transistorsoft/nativescript-background-geolocation-lt#105]
## Your Environment
* Plugin version: 1.8
* Platform: Android. Possibly iOS
* OS version: Any
* Device manufacturer / model: Any
* Nativescript version (`tns info`): 3.4.1
* Plugin config

I published an app update yesterday and today I have had two complaints that all data has been lost from the device after updating.  I've just tested this myself and indeed the database seems to be cleared when updating.

I have a separate SQLite database that I maintain myself within the app and this is preserved between updates.

What is the reason for the removal of data and can this behaviour be changed?

**Comment by christocracy** [comment]
How old was were the records in the datbase?  What is your `maxDaysToPersist` configured to?

**Comment by 3rror404** [comment]
I don't think it's related to `maxDaysToPersist` - though that has stung me in the past. I have it set to 365 days now.

The data lost was recorded today. I think the update probably happened whilst the plugin was recording. 

I'm trying to get some more info from a user now...

**Comment by 3rror404** [comment]
I can't get in touch with the user. However, I updated my test device that was running a dev build to the latest version from the PlayStore and this did seem to lose it's location data - but not my own database or ApplicationSettings. I'm not sure how I can double check this as the Play Store no longer offers me an update option even after lowering the version code and number in my dev app

**Comment by 3rror404** [comment]
I'm not convinced the update was the issue. Sorry. I'll close this for now until I figure out what happened to the missing data.
