### ISSUE TITLE
failure is not a function. (In 'failure(status)', 'failure' is undefined)

### ISSUE THREAD

**Issue by 3rror404** [transistorsoft/nativescript-background-geolocation-lt#106]
## Your Environment
* Plugin version: 1.8.0
* Platform: iOS
* OS version: 10.3.2
* Device manufacturer / model: iPhone 6
* Nativescript version (`tns info`): 
```
┌──────────────────┬─────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 3.4.2           │ 3.4.3          │ Update available │
│ tns-core-modules │ 3.4.1           │ 3.4.1          │ Up to date       │
│ tns-android      │ 3.4.1           │ 3.4.1          │ Up to date       │
│ tns-ios          │ 3.4.1           │ 3.4.1          │ Up to date       │
└──────────────────┴─────────────────┴────────────────┴──────────────────┘
```

I've had few crashes reported on iOS since updating my app. All seem to happen as soon as the app opens - this is when the plugin is configured.

I managed to briefly get hold of one of the devices that is crashing and it looks like it's something to do with the background-fetch plugin. 

This is the error displayed in XCode's console:

```
 JavaScript stack trace:
 1   @file:///app/tns_modules/nativescript-background-fetch/background-fetch.js:16:24
 2   UIApplicationMain@[native code]
 3   start@file:///app/tns_modules/tns-core-modules/application/application.js:258:26
 4   anonymous@file:///app/app.js:37:18
 5   evaluate@[native code]
 6   moduleEvaluation@[native code]
 7   @[native code]
 8   promiseReactionJob@[native code]
 JavaScript error:
 file:///app/tns_modules/nativescript-background-fetch/background-fetch.js:16:24: JS ERROR TypeError: failure is not a function. (In 'failure(status)', 'failure' is undefined)
```

I initialise background fetch in the same way as your demo app:

app.ts

```
if (application.ios) {
  class MyDelegate extends UIResponder implements UIApplicationDelegate {
    public static ObjCProtocols = [UIApplicationDelegate];

    public applicationPerformFetchWithCompletionHandler(application: UIApplication, completionHandler:any) {
      BackgroundFetch.performFetchWithCompletionHandler(application, completionHandler);
    }
  }
  application.ios.delegate = MyDelegate;
}
```

view model

```
BackgroundFetch.status((status) => {
      //console.log('- BackgroundFetch status: ', status);
    });
    // Listen to iOS-only BackgroundFetch events. 
    BackgroundFetch.configure({ stopOnTerminate: false }, () => {
      //console.log('[event] BackgroundFetch');
      BackgroundFetch.finish(UIBackgroundFetchResult.NewData);
    });
```

Strangely this does not happen on every device. I've never experienced it myself but for those that do, it happens every single time they open the app. I've had reports on iOS 10.x and 11.x and devices ranging from iPhone 6 to iPhone X.

Any ideas?

**Comment by 3rror404** [comment]
Figured out why this is happening. If "Background App Refresh" is disabled in iOS settings the app will crash. The same happens in your demo app.
How do I work around this?

**Comment by christocracy** [comment]
The plugin is able to function without background-fetch yes.  `BackgroundGeolocation` uses fetch events internally for a number of things, including evaluating schedules (if you're using the scheduler).  The plugin will also sample the motion API during a fetch event to assist with triggering tracking.  

It looks like you could solve your issue simply by providing a `failureFn` to [`BackgroundFetch#configure`](https://github.com/transistorsoft/nativescript-background-fetch/blob/master/background-fetch.ios.ts#L14)

The `#configure` method *should* be initializing `failure` like so:
```javascript
public static configure(config:Object, callback:Function, failure?:Function) {
  failure = failure || emptyFn
  .
  .
  .
}
```
Just as the [`#start`](https://github.com/transistorsoft/nativescript-background-fetch/blob/master/background-fetch.ios.ts#L30) method does.

Simply provide a `failureFn` to `#configure` and all your problems are solved.
