### ISSUE TITLE
Difference between `geofenceProximityRadius` in configure(..) and `radius` in addGeofence(..)

### ISSUE THREAD

**Issue by Liooo** [transistorsoft/nativescript-background-geolocation-lt#107]
what's the difference between those 2 parameters?

**Comment by christocracy** [comment]
See [Geofencing](https://github.com/transistorsoft/nativescript-background-geolocation-lt/blob/master/docs/geofencing.md)

- `radius` is the radius of the geofence you wish to monitor.
- `geofenceProximityRadius` is used for determining *which* geofences to activate.

**Comment by Liooo** [comment]
ohh that's quite obvious from that figure, sorry for bothering and thanks!
