### ISSUE TITLE
 Property 'onLocation' does not exist on type 'AppComponent'.

### ISSUE THREAD

**Issue by MuhammadTahir92** [transistorsoft/nativescript-background-geolocation-lt#109]
i am using in nativescript angular project and all event listeners show's this error
![image](https://user-images.githubusercontent.com/25048331/38555420-6f9eb8a6-3cdf-11e8-8a48-52df59d31fbf.png)

this is my code in app.component.ts
` private _state: any;

  constructor() {

    // 1. Listen to events
    BackgroundGeolocation.on("location", this.onLocation.bind(this));
    BackgroundGeolocation.on("motionchange", this.onMotionChange.bind(this));
    BackgroundGeolocation.on("http", this.onHttp.bind(this));
    BackgroundGeolocation.on("heartbeat", this.onHeartbeat.bind(this));
    BackgroundGeolocation.on("schedule", this.onSchedule.bind(this));
    BackgroundGeolocation.on("error", this.onError.bind(this));

    // 2. Configure it.
    BackgroundGeolocation.configure({
      debug: true,
      desiredAccuracy: 0,
      stationaryRadius: 25,
      distanceFilter: 50,
      activityRecognitionInterval: 10000,
      url: 'http://localhost:8080/locations',
      autoSync: true
    }, (state) => {
      // 3. Plugin is now ready to use.
      if (!state.enabled) {
        BackgroundGeolocation.start();
      }
    });
    // NOTE:  Do not execute *any* method which access location-services until
    //  the callback to #configure method executes:

  
}`

How can i implement this with angular nativescript please guide with some details step by step

**Comment by christocracy** [comment]
That example code you pasted *assumes* the existence of those functions *in YOUR* app component.

*YOU* have to define those functions.
