### ISSUE TITLE
Permission exception if I call GetCurrentPosition before calling Start/Stop

### ISSUE THREAD

**Issue by AlphaCreativeDev** [transistorsoft/nativescript-background-geolocation-lt#114]
## Your Environment
* Plugin version: 1.8.0 (from master as of 6/21/2018)
* Platform: Android
* OS version: 8.1
* Device manufacturer / model:  Pixel 2 or emulator.  Both have the issue.
* Android SDK Tools: 26.1.1
* Android SDK Build Tools: 27.0.3
* Nativescript version (`tns info`):
```
√ Getting NativeScript components versions information...
‼ Update available for component nativescript. Your current version is 4.1.0 and the latest available version is 4.1.1.
√ Component tns-core-modules has 4.1.0 version and is up to date.
√ Component tns-android has 4.1.3 version and is up to date.
× Component tns-ios is not installed.
```

* Plugin config
```
BackgroundGeolocation.getCurrentPosition(function(location) {
            // This location is already persisted to plugin’s SQLite db.  
            // If you’ve configured #autoSync: true, the HTTP POST has already started.
            console.log("- Current position received: ", location);
          }, function(errorCode) {
            alert('An location error occurred: ' + errorCode);
          }, {
            timeout: 30,      // 30 second timeout to fetch location
            maximumAge: 5000, // Accept the last-known-location if not older than 5000 ms.
            desiredAccuracy: 10,  // Try to fetch a location with an accuracy of `10` meters.
            samples: 3,   // How many location samples to attempt.
            extras: {         // [Optional] Attach your own custom `metaData` to this location.  This metaData will be persisted to SQLite and POSTed to your server
              foo: "bar"  
            }
          });
```
I tried adding the getCurrentPosition call in the success event of config but the error persisted.
```
BackgroundGeolocation.setConfig({
  desiredAccuracy: 10,
  distanceFilter: 10
}, function() {
  console.log('set config success');
}, function() {
  console.log('failed to setConfig');
});
```
## Expected Behavior

Should automatically set permissions so we can call GetCurrentPosition without starting/stopping the background service.

## Actual Behavior

Does not set permissions and throws exception.
```
An uncaught Exception occurred on "GoogleApiHandler" thread.
java.lang.SecurityException: Client must have ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to perform any location operations.
	at android.os.Parcel.readException(Parcel.java:2004)
	at android.os.Parcel.readException(Parcel.java:1950)
	at com.google.android.gms.internal.zzeu.zza(Unknown Source:10)
	at com.google.android.gms.internal.zzcfa.zzif(Unknown Source:9)
	at com.google.android.gms.internal.zzcfd.getLastLocation(Unknown Source:19)
	at com.google.android.gms.internal.zzcfk.getLastLocation(Unknown Source:2)
	at com.google.android.gms.location.zzg.zza(Unknown Source:2)
	at com.google.android.gms.common.api.internal.zze.zza(Unknown Source:8)
	at com.google.android.gms.common.api.internal.zzbo.zzb(Unknown Source:9)
	at com.google.android.gms.common.api.internal.zzbo.zzaiw(Unknown Source:82)
	at com.google.android.gms.common.api.internal.zzbo.onConnected(Unknown Source:16)
	at com.google.android.gms.common.internal.zzac.onConnected(Unknown Source:2)
	at com.google.android.gms.common.internal.zzn.zzakr(Unknown Source:131)
	at com.google.android.gms.common.internal.zze.zzw(Unknown Source:64)
	at com.google.android.gms.common.internal.zzi.zzaks(Unknown Source:52)
	at com.google.android.gms.common.internal.zzh.handleMessage(Unknown Source:270)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)

```

## Steps to Reproduce

1. tns create MyTestApp --tsc
2. cd MyTestApp
3. tns plugin add nativescript-background-geolocation-lt
4. tns platform remove android
5. tns platform add android
6. I added the getCurrentPosition call in the onTap event in the template installed.  
7. tns run android
8. tap button
9.  (Optional) - I tried running config first before calling getCurrentPosition but the error persists.  

## Context

Get Current Position without background tracking.  We have a use case that depending on user settings they may be tracked in the background or may not but we do need to get their current position based on certain actions taking in the application.  

## Debug logs

[error.log](https://github.com/transistorsoft/nativescript-background-geolocation-lt/files/2124161/error.log)

**Comment by christocracy** [comment]
I have a big refactor coming soon.  The Android plugin now handles perrmissions internally within plugin.

**Comment by AlphaCreative** [comment]
Thanks for your response. We knew you had a big refactor coming with the Cordova version but we weren't sure about the NativeScript version.  We are switching from Cordova to NativeScript.  Starting and stopping the bg service before calling getCurrentPosition is our current work around.  We will do that while we wait on the new version.

**Comment by christocracy** [comment]
It’s pretty much ready.  I’m going to publish a beta tomorrow.

**Comment by christocracy** [comment]
`1.9.0-beta.2` is now published.

**Comment by christocracy** [comment]
`1.9.0.beta.3` released.  Be sure to [do this](https://github.com/transistorsoft/nativescript-background-geolocation-lt#android-setup).

**Comment by AlphaCreativeDev** [comment]
Closing this old issue.
