### ISSUE TITLE
Dynamically enabling/disabling the HTTP feature

### ISSUE THREAD

**Issue by neil-119** [transistorsoft/nativescript-background-geolocation-lt#124]
I need to enable the [HTTP feature](https://github.com/transistorsoft/nativescript-background-geolocation-lt/blob/master/docs/http.md) and add an auth [header](https://github.com/transistorsoft/nativescript-background-geolocation-lt/tree/master/docs#config-object-headers) when the user is logged in, but disable that feature when the user isn't logged in. But it seems that the `ready()` method expects these on init, and `setConfig()` doesn't take effect until the app is restarted. So how can I enable http and later disable it at runtime? Thanks!

iOS / Android version: iOS 11.4.1, Android 8.1, Android 9.0
NativeScript version: 4.2.0 (incl. latest runtimes)
Plugin version: latest

**Comment by christocracy** [comment]
`#ready` only consumes the supplied config at first install of your app.

You should always `#ready` the plugin, regardless of logged-in / not.

```typescript
export class HelloWorldModel extends Observable {

  private _location: string;
  private _counter: number;
  private _message: string;
  private _isMoving: boolean;
  private _enabled: boolean;
  private _paceButtonIcon: string;

  constructor() {
    BackgroundGeolocation.on('location', (location) => { ... });

    BackgroundGeolocation.ready({
      url: '...',      
    }, (state) => {
      console.log('[ready] BackgroundGEolocation');
      // NOTE:  we do NOT start tracking until we know user is logged in.
    });
  }
  
  onLogin() {
    BackgroundGeolocation.setConfig({
      headers: {"X-FOO", "bar"}
    }, (state) => {
      // Now that user is logged in, start tracking them.
      BackgroundGeolocation.start();
    });
  }

  onLogout() {
    // Presumably you no longer want to track users when they're logged out.  Just turn off the plugin.
    BackgroundGeolocation.stop();
  }
}
```

**Comment by neil-119** [comment]
Super, thanks.
