### ISSUE TITLE
Don't ask for Fitness / Activity permission?

### ISSUE THREAD

**Issue by neil-119** [transistorsoft/nativescript-background-geolocation-lt#126]
For my app, not all users rely on the GPS. For these users, I _don't_ want to ask for fitness / activity permissions when the app launches. Any ideas?

**Comment by christocracy** [comment]
[`disableMotionActivityUpdates: true`](https://github.com/transistorsoft/nativescript-background-geolocation-lt/tree/master/docs#config-boolean-disablemotionactivityupdates-false)
