### ISSUE TITLE
[iOS] 'UIApplicationState' is not assignable to parameter of type 'Function'.

### ISSUE THREAD

**Issue by FranciZ** [transistorsoft/nativescript-background-geolocation-lt#130]
## Your Environment
* Plugin version: 1.8.0
* Platform: iOS
* OS version: 11
* Device manufacturer / model: Apple
* Nativescript version 4.2.0
* Plugin config

## Expected Behavior
iOS should build without errors. I have `references.d.ts` setup as well as `tsconfig` as in README.

## Actual Behavior
```
'UIApplicationState' is not assignable to parameter of type 'Function'.
```

Error happens on line:
```
BackgroundFetch.performFetchWithCompletionHandler(completionHandler, application.applicationState);
```

## Steps to Reproduce

Create a new project and paste the iOS setup code in it as suggested. Build.

## Context
Build for iOS.

## Debug logs
```
app/main.ts(18,76): error TS2345: Argument of type 'UIApplicationState' is not assignable to parameter of type 'Function'.
```

**Comment by christocracy** [comment]
I think your problem is you're following the README instructions from master (which corresponds to version `1.9.0-beta.4`) with an older version you're using (1.8.0).

**Comment by FranciZ** [comment]
Could you point me to a solution maybe? I can't really upgrade the plugin since https://github.com/transistorsoft/nativescript-background-geolocation-lt/issues/121 still persists.

**Comment by christocracy** [comment]
If you're going to use a version other than latest, you must select the **Tag -> 1.8.0** and browse *that* tree.
![](https://dl.dropboxusercontent.com/s/nmr550h95lqhssg/Screenshot%202018-10-25%2009.10.34.png?dl=1)

**Comment by FranciZ** [comment]
Thanks!
