### ISSUE TITLE
Background Location Request Device Idle Android 8.0

### ISSUE THREAD

**Issue by denisraison** [transistorsoft/nativescript-background-geolocation-lt#131]
## Your Environment
* Plugin version: 1.9.0-beta.4
* Platform: Android
* OS version: Android 8.0
* Device manufacturer / model: Emulator Google Pixel 2XL
* Nativescript version (`tns info`): Component nativescript has 4.2.4 version and is up to date.
* Plugin config
```
const config = {
    reset: true, // REMOVE IT BEFORE COMMIT!
    debug: true,
    logLevel: 5,
    maxDaysToPersist: 7,
    stopOnTerminate: false,
    startOnBoot: true,
    preventSuspend: true,
    foregroundService: true,
    forceReloadOnBoot: true,
    forceReloadOnMotionChange: true,
    forceReloadOnLocationChange: true,
    notificationText: "Tap to open",
    notificationSmallIcon: "drawable/icon_notification",
  }
```

## Expected Behavior
Get current location when running in background mode and the device is idle

## Actual Behavior
When we call getCurrentPosition({ timeout: 30, maximumAge: 10000, desiredAccuracy: 10}) it's always timing out. 
We're reading the[ Android 8.0 docs](https://developer.android.com/about/versions/oreo/background-location-limits) and we saw that they've changed the limits for background locations requests (to save battery). But our app is running a foreground service and that should make it works, I guess.

## Steps to Reproduce
1. Run your code using a device with Android 8.0 and above
2. Run the BackgroundGeolocation.ready(config) using the config provided.
3. Put your device to idle mode by running on your console:
> adb shell dumpsys deviceidle enable
> adb  shell dumpsys deviceidle force-idle
> adb  shell dumpsys deviceidle step
> adb  shell  dumpsys battery unplug

4. Use a notification system or a timer to make your code call BackgroundGeolocation.getCurrentPosition()

## Context
We the app receives a notification we want to get the current location and respond to the server. We want to do it even when it's on idle mode.

## Debug logs
10-29 11:35:36.800 18173 18173 E TSLocationManager: [c.t.l.l.TSLocationManager getLastLocation]
10-29 11:35:36.800 18173 18173 E TSLocationManager:   ‼️  Failed to get last location: com.google.android.gms.tasks.zzu@55e0cc3
10-29 11:35:36.838 18173 18594 D TSLocationManager: [c.t.locationmanager.util.b a]
10-29 11:35:36.838 18173 18594 D TSLocationManager:   ℹ️  LocationAuthorization: Permission granted
10-29 11:35:41.383 18173 18173 W TSLocationManager: [c.t.l.l.SingleLocationRequest e]
10-29 11:35:41.383 18173 18173 W TSLocationManager:   ⚠️  timeout: 13
10-29 11:35:41.404 18173 18569 W TSLocationManager: [c.t.l.l.TSLocationManager onLocationTimeout]
10-29 11:35:41.404 18173 18569 W TSLocationManager:   ⚠️  TSLocationManager received location timeout
10-29 11:35:41.435 18173 18173 W TSLocationManager: [c.t.l.a.BackgroundGeolocation _onLocationError]
10-29 11:35:41.435 18173 18173 W TSLocationManager:   ⚠️  Location error: 408

## Note
We're evaluating the plugin before buying a licence for it. We want to test if it's going to attend all our needs and intentions.

Thank you

**Comment by christocracy** [comment]
This has nothing to do with background-execution limits.  Location error 408 means the native location API failed to provide a location within the `timeout` period.  This can happen for a number of reasons:

- Underground in a subway.
- Driving through a tunnel
- Settings->Location->Mode:  Device Only (ie: GPS only) and you're not outdoors.
- Wifi Disabled

**Comment by denisraison** [comment]
Hi Chis,

Thanks for replying it.
But it's weird that just by removing the device from the idle mode the getCurrentPosition() function works.

**Comment by christocracy** [comment]
I don't see anything weird here.

**Comment by denisraison** [comment]
Ok then.
