### ISSUE TITLE
"noEmitHelpers": true, - crash my app

### ISSUE THREAD

**Issue by karo-dc** [transistorsoft/nativescript-background-geolocation-lt#134]
when I exclude 'noEmitHelpers' from tsconfig I got exception
.
.
.
.

***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x1017d773c NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool, bool)
2   0x101808068 -[TNSRuntime executeModule:referredBy:]
3   0x100c0c748
4   0x184d7dfc0 <redacted>
JavaScript stack trace:
1   __@file:///app/bundle.js:3120:29
2   @file:///app/bundle.js:3121:90
3   @file:///app/bundle.js:3126:14
4   ./services/custom-app-delegate.ts@file:///app/bundle.js:3135:2
5   __webpack_require__@file:///app/bundle.js:76:34
6   @file:///app/bundle.js:2917:48
7   ./app.ts@file:///app/bundle.js:2947:34
8   __webpack_require__@file:///app/bundle.js:76:34
9   checkDeferredModules@file:///app/bundle.js:45:42
10  @file:///app/bundle.js:149:38
11  anonymous@file:///app/bundle.js:150:12
12  evaluate@[native code]
13  moduleEvaluation@[native code]
14  @[native code]
15  promiseReactionJob@[native code]
16  require@[native code]
17  anonymous@file:///app/starter.js:2:8
18  evaluate@[native code]
19  moduleEvaluation@[native code]
20  @[native code]
21  promiseReactionJob@[native code]
JavaScript error:
file:///app/bundle.js:3120:29: JS ERROR TypeError: Attempted to assign to readonly property.
*** JavaScript call stack:
(
)
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: Attempted to assign to readonly property.
at
1   __@file:///app/bundle.js:3120:29
2   @file:///app/bundle.js:3121:90
3   @file:///app/bundle.js:3126:14
4   ./services/custom-app-delegate.ts@file:///app/bundle.js:3135:2
5   __webpack_require__@file:///app/bundle.js:76:34
6   @file:///app/bundle.js:2917:48
7   ./app.ts@file:///app/bundle.js:2947:34
8   __webpack_require__@file:///app/bundle.js:76:34
9   checkDeferredModules@file:///app/bundle.js:45:42
10  @file:///app/bundle.js:149:38
11  anonymous@file:///app/bundle.js:150:12
12  evaluate@[native code]
13  moduleEvaluation@[native code]
14  @[native code]
15  promiseReactionJob@[native code]
16  require@[native code]
17  anonymous@file:///app/starter.js:2:8
18  evaluate@[native code]
19  moduleEvaluation@[native code]
20  @[native code]
21  promiseReactionJob@[native code]
', reason: '(null)'
*** First throw call stack:
(0x185426d8c 0x1845e05ec 0x1017d7<\M-b\M^@\M-&>

**Comment by karo-dc** [comment]
if I add that property, app does not launch

**Comment by christocracy** [comment]
*****************************************************************
* WARNING:  If you ignore this template, your issue will be too.
*****************************************************************



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Nativescript version (`tns info`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs
