### ISSUE TITLE
Sometimes it just dies when in debug.

### ISSUE THREAD

**Issue by caiusCitiriga** [transistorsoft/nativescript-background-geolocation-lt#138]
## Your Environment
* Plugin version: 1.9.1
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: OnePlus 5T
* Nativescript version (`tns info`): 5.1.0
* Plugin config: 

```ts
BackgroundGeolocation.ready({
            debug: true,
            reset: true, // issue tmp fix when navigating back from another app to this (?)

            autoSync: true,
            startOnBoot: true,
            desiredAccuracy: 0,
            distanceFilter: 10,
            stationaryRadius: 20,
            enableHeadless: false,
            stopOnTerminate: false,
            foregroundService: true,
            forceReloadOnBoot: true,
            activityRecognitionInterval: 5000,

            method: 'PUT',
            httpRootProperty: 'location',
            url: `${this._actualBackendEndpoint}devices/user/${this._user}/device/${this._deviceUID}/location`,

            notificationTitle: 'Shelly',
            notificationText: 'Servizio di notifica',
            notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_HIGH,
        }, (state) => {
            // 3. Plugin is now ready to use.
            if (!state.enabled) {
                BackgroundGeolocation.start();
            }
            this._$geolocationStarted.next(true);
        });
```

## Expected Behavior
I'm exepecting that setting the config in `forgroundService` and `stopOntTerminate: false` would keep the service alive **forever**

## Actual Behavior
In some randomic occasions the service just dies. No errors, nothing at all. It's like it's being killed by the OS, but with no particular reason, since there was no memory pressure. 

I thought it was a `debug mode limitation`. So when purchasing the full version this thing wouldn't be present. Or is it something that you've never experienced?

## Steps to Reproduce
1 Install the app

2 Run it

3 Kill it

4 Wait for it to be definetively killed with the service too (Unfortunately the thing is totally random. I couldn't say how to reproduce it.)

## Context
Just keeping the service alive forever

**Comment by christocracy** [comment]
See the *OnePlus* section of [this link](https://dontkillmyapp.com/)

**Comment by caiusCitiriga** [comment]
@christocracy What a sad story. Thank you for sharing with me this, even if sad, it's precious information. Well, I guess that we're left by our own then 😅

Thank you again. Closing it.
