### ISSUE TITLE
undefined: JS ERROR Error: Could not find module './'.

### ISSUE THREAD

**Issue by AndersGerner** [transistorsoft/nativescript-background-geolocation-lt#14]
I have tried on 2 different macs, and I keep getting this error:

```
Project successfully built.
Using  /Users/agn/Development/nativescript-background-geolocation-lt/demo/platforms/ios/build/emulator/demo.app
Starting iOS Simulator
Oct  4 10:29:30 AG-MBP-WORK demo[29435]: 1   0x104ab38d7 -[TNSRuntime executeModule:]
Oct  4 10:29:30 AG-MBP-WORK demo[29435]: 2   0x1013f6582 main
Oct  4 10:29:30 AG-MBP-WORK demo[29435]: 3   0x106e3592d start
Oct  4 10:29:30 AG-MBP-WORK demo[29435]: undefined: JS ERROR Error: Could not find module './'. Computed path '/Users/agn/Library/Developer/CoreSimulator/Devices/2D044DFF-B201-47D1-8718-449EBF7275CB/data/Containers/Bundle/Application/32DEA80B-FAE4-4D2B-A94B-0A046EE94DE3/demo.app/app'.
Oct  4 10:29:30 AG-MBP-WORK com.apple.CoreSimulator.SimDevice.2D044DFF-B201-47D1-8718-449EBF7275CB.launchd_sim[27817] (UIKitApplication:com.transistorsoft.backgroundgeolocation.nativescript[0x62f0][29435]): Service exited due to signal: Segmentation fault: 11
```

How can i solve this? I have executed the commands for running the demo, as the frontpage explains.

**Comment by 3rror404** [comment]
Hey @AndersGerner,

I had the same issue. See this thread https://github.com/transistorsoft/nativescript-background-geolocation-lt/issues/10. Downgrading TypeScript got it working for me.

**Comment by christocracy** [comment]
This error means the `/demo` didn't get it's `.ts` files compiled to `.js`.  Maybe I should just compile the demo files to .js and commit them to the repo.

**Comment by christocracy** [comment]
I did a big refactor of the API with breaking changes in branch [refactor-api](https://github.com/transistorsoft/nativescript-background-geolocation-lt/pull/19)

You'll no longer create an instance of `BackgroundGeolocation` -- all the methods are static now.  This will make it easier interacting with the plugin over multiple views.

**Comment by christocracy** [comment]
The error:
```
JS ERROR Error: Could not find module './'.
```
is due to the demo's `.js` files failing to compile using `typescript@2.0.3`.  I have no idea why but it sees similar to [this issue](https://github.com/NativeScript/NativeScript/issues/2698)

Install `1.8.10`
```
$ npm install -g typescript@1.8.10
```

**Comment by christocracy** [comment]
This issue should be obsolete with latest version `1.3.2`
