### ISSUE TITLE
Parsing JSON in VB.NET

### ISSUE THREAD

**Issue by mrwrighty** [transistorsoft/nativescript-background-geolocation-lt#143]
## Your Environment
* Plugin version: 1.91
* Platform: iOS
* OS version: 12.1.4
* Device manufacturer / model: iPhone X
* Nativescript version (`tns info`):
* Plugin config

## Expected Behavior
Cannot parse JSON in vb.net

## Actual Behavior

JSON response from plugin is 

{"location":{"coords":{"speed":17.57,"longitude":-2.1644961191045793,"floor":null,"latitude":52.208792196692841,"accuracy":8,"altitude_accuracy":9.0999999999999996,"altitude":34.100000000000001,"heading":203.72999999999999},"extras":{},"is_moving":true,"odometer":91120.699999999997,"uuid":"34E91A24-75C1-41DB-B523-D22BF1B0ECD6","activity":{"type":"unknown","confidence":100},"battery":{"level":1,"is_charging":true},"timestamp":"2019-02-27T17:57:23.000Z"}}

JSON expected is:

{"location":[{"coords":[{"speed":17.57,"longitude":-2.1644961191045793,"floor":null,"latitude":52.208792196692841,"accuracy":8,"altitude_accuracy":9.0999999999999996,"altitude":34.100000000000001,"heading":203.72999999999999}],"extras":{},"is_moving":true,"odometer":91120.699999999997,"uuid":"34E91A24-75C1-41DB-B523-D22BF1B0ECD6","activity":{"type":"unknown","confidence":100},"battery":{"level":1,"is_charging":true},"timestamp":"2019-02-27T17:57:23.000Z"}]}

## Steps to Reproduce
Remove [] from JSON array 
1.
2.
3.
4.

## Context
 Parse JSON in vb.net

**Comment by christocracy** [comment]
If you want your own custom template, provide one.  [locationTemplate](https://github.com/transistorsoft/nativescript-background-geolocation-lt/tree/master/docs#config-string-locationtemplate-undefined)

**Comment by mrwrighty** [comment]
Using this template locationTemplate: 
httpRootProperty: 'location',
locationTemplate: '[{"lat":<%= latitude %>,"lng":<%= longitude %>,"heading": <%= heading %>,"speed":<%= speed %> }]',

Results in this output {"location":[{"lng":-2.1281124147734172,"lat":52.000321439890222,"speed":-1,"heading":-1},{}]}

The ,{} is not required.
