### ISSUE TITLE
Timestamp 1 hour out

### ISSUE THREAD

**Issue by mrwrighty** [transistorsoft/nativescript-background-geolocation-lt#149]
I'm using <%=timestamp%>  in the JSON locationTemplate but the actual timestamp is 12 hour earlier than the actual time. I'm assuming this is because it is GPS time and not device time.

Based on that assumption I guess I have to handle the clock changes between British Summer time and Winter Time. Is my assumption correct.

**Comment by christocracy** [comment]
Are you aware the timestamp is in UTC (not local time).  Perhaps you're on the other side of Greenwich?

**Comment by mrwrighty** [comment]
Yep my bad, apologies. When I capture the timestamp I also capture a logtime from the physical device so am using that. Thank you.
