### ISSUE TITLE
Battery Drain

### ISSUE THREAD

**Issue by mrwrighty** [transistorsoft/nativescript-background-geolocation-lt#150]
Hi

Using this function in iOS and it is working amazingly well. However we do have an issue with battery drain. Other than reducing the frequency of locations would it be feasible to adjust location frequency for example if the battery drops below say 20% or some customisable value so that it can be enabled or disabled in the config settings. I realise the plugin has battery management to a point, i.e sleeps when no movement, but maybe another option as suggested would be useful.

At 70mph I'm getting a reading about every 1 minute based on the following settings:-

`logLevel: nativescript_background_geolocation_lt_1.BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            desiredAccuracy: nativescript_background_geolocation_lt_1.BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
            distanceFilter: 75,
            stopTimeout: 1,
            elasticityMultiplier: 3,
            autoSync: true,
            stopOnTerminate: false,
            startOnBoot: true,
            foregroundService: true,
            preventSuspend: true,
            heartbeatInterval: 60*30,
            httpRootProperty: 'location',`

**Comment by christocracy** [comment]
You’re free to execute #setConfig at any time.  The battery level is provided to each location emitted to location event.

Be aware that http requests are a big consumer of battery.
