### ISSUE TITLE
Reasoning behind depracation?

### ISSUE THREAD

**Issue by Spacarar** [transistorsoft/nativescript-background-geolocation-lt#152]
This is more of a question than an issue. Thanks for providing all the awesome plugins you provide. The company I work for has been working on developing a nativescript application for a few months now and had planned on using this plugin in our application and today I had someone ask on the nativescript slack about how to do background geolocation in android and I had directed them here only to find the plugin for nativescript has been deprecated.

I was just wondering what some of the reasoning behind this change has been? In my search I also came across this question https://discourse.nativescript.org/t/gps-in-background/4435. which stated to be advised against using the plugin. Could this be because Nativescript 6 is going to be able to handle this feature natively instead of needing a plugin?

Just looking for some answers on what to do looking towards the future. At our company we have been debating ditching Nativescript all together for something else like Cordova and if this really has been deprecated with no alternative then we may just have to do that.

Once again thanks for the awesome plugins you have provided over the years and any response to this issue

**Comment by christocracy** [comment]
I’ve grown to dislike NativeScript and its popularity is waning now.

I’ve made more sales for the new Flutter version in 6 months than NativeScript in 2+ years.  The Cordova and React Native versions remain strongly supported as well, for over 4 years now.

I highly recommend ditching NativeScript in favor of Flutter (or Cordova, React Native).
