### ISSUE TITLE
Cannot find name TSBackgroundFetch

### ISSUE THREAD

**Issue by marciovicente** [transistorsoft/nativescript-background-geolocation-lt#18]
Hey, I'm trying to use this plugin but on `tns build ios` step I'm getting this error
```
app/app.ts(7,9): error TS2304: Cannot find name 'TSBackgroundFetch'
```

![image](https://cloud.githubusercontent.com/assets/1021901/19368206/5cddd1b4-9175-11e6-987f-ac6c8b7ccc35.png)

Any ideas about this?

**Comment by christocracy** [comment]
Did you first try the demo?

**Comment by christocracy** [comment]
Do you have `nodes_modules/nativescript-background-fetch`?

**Comment by marciovicente** [comment]
yeah, I have!

**Comment by christocracy** [comment]
Try adding top-of-file:
```Javascript
declare var TSBackgroundFetch: any;
```

**Comment by marciovicente** [comment]
It's solved this specific issue, but now I'm getting
```
file:///app/home/model.js:5:36: JS ERROR Error: Could not find module 'nativescript-background-geolocation-lt'. Computed path '/var/mobile/Containers/Data/Application/F275751B-8D12-4523-91D2-D447E98206FB/Library/Application Support/LiveSync/app/tns_modules/nativescript-background-geolocation-lt'.
```

I've tried:
```javascript
const BackgroundGeolocation = require("nativescript-background-geolocation-lt").BackgroundGeolocation;
```
and
```javascript
import { BackgroundGeolocation } from "nativescript-background-geolocation-lt";
```
But this error persists in both cases.

**Comment by christocracy** [comment]
I'm not sure what that's about, I'm still learning typescript, but I get the same error when I compile the demo.  See the demo's [tsconfig.json](https://github.com/transistorsoft/nativescript-background-geolocation-lt/blob/master/demo/tsconfig.json)

**Comment by christocracy** [comment]
Ok, it has to do with `typings`, the `package.json` isn't declaring one.  I've been looking at a bunch of other nativescript plugins trying to find the best way to handle this.  It seems I have to provide a `background-geolocation.d.ts` and I can't provide a platform-specific one `background-geolocation.android.d.ts` / `background-geolocation.ios.d.ts`.

What a pain.

**Comment by christocracy** [comment]
Ok, I refactored the API, referencing a definitions file from `package.json`.  This should solve the issue of 
```
JS ERROR Error: Could not find module 'nativescript-background-geolocation-lt'
```

I'll have to do the same now for `TSBackgroundFetch`, but that API is *much* simpler.

Please try out branch [refactor-api](https://github.com/transistorsoft/nativescript-background-geolocation-lt/tree/refactor-api)

**NOTE** You must no longer create an instance of `BackgroundGeolocation` -- All its methods are **static** now:
**OLD**
```Javascript
import {BackgroundGeolocation} from "nativescript-background-geolocation-lt"

export class MapModel extends observable.Observable {
  constructor() {
    super();
    this._bgGeo = new BackgroundGeolocation();
    this._bgGeo.configure(yourConfig, function(state) {
        console.log('- State: ', state);
    });
  }
}
```
**NEW**
```Javascript
import {BackgroundGeolocation} from "nativescript-background-geolocation-lt"

export class MapModel extends observable.Observable {
  constructor() {
    super();
    BackgroundGeolocation.configure(yourConfig, function(state) {
        console.log('- State: ', state);
    });
  }
}
```

I need fix the docs about this.

**Comment by marciovicente** [comment]
Nice change but it stills doesn't works for me.. I've installed the latest plugin version from master branch and tried to use the both imports type. 😞

**Comment by christocracy** [comment]
It failed building the demo?

**Comment by christocracy** [comment]
```
┌──────────────────┬─────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 2.3.0           │ 2.3.0          │ Up to date       │
│ tns-core-modules │ 2.3.0           │ 2.3.0          │ Up to date       │
│ tns-android      │ 2.1.0           │ 2.3.0          │ Update available │
│ tns-ios          │ 2.3.0           │ 2.3.0          │ Up to date       │
└──────────────────┴─────────────────┴────────────────┴──────────────────┘

$ tsc --version
Version 1.8.10

$ npm -v
3.10.3

$ node -v
v6.3.1
```

**Comment by christocracy** [comment]
Ok, I see the issues.  I've got the plugin running on a few new Hello World app.

**1** You can't simply `tns plugin add https://path/to/github`, since the github repo doesn't contain compiled `.js` files.  The Github repo purposely [`.gitignore`s `*.js` files](https://github.com/transistorsoft/nativescript-background-fetch/blob/master/.gitignore#L2).

Since the `background-geolocation.js` doesn't exist, this is why you see:
```
error TS2307: Cannot find module 'nativescript-background-geolocation'
```

**Solution**:  Clone the repo and compile the `.js` files, *then* `tns plugin add /path/to/repo`.
```
$ git clone https://github.com/transistorsoft/nativescript-background-geolocation-lt.git
$ cd nativescript-background-geolocation-lt
$ npm install
$ tsc
```
The plugin is compiled and ready to install into your app.
```
$ cd YourApp
$ tns plugin add /path/to/nativescript-background-geolocation-lt
```

**2** `BackgroundFetch`.  Since `nativescript-background-fetch` is declared as a dependency of `background-geolocation-lt`, `tns plugin add ..` doesn't add the dependency to the root `node_modules` folder, it gets add to `nativescript-background-geolocation-lt/node_modules`.  This causes the path to background-fetch's Podspec to be incorrect.  This is not how `npm install` operates.  If I `npm install nativescript-background-geolocation-lt`, all child dependencies are added the root `node_modules`.

**Solution**.  I'll have to remove `background-fetch` as a dependency and instruct users to explicitly `tns plugin add nativescript-background-fetch`

**Comment by marciovicente** [comment]
@christocracy something weird it's happening right now. My VSCode already knowing the plugin (image below), but in the emulator or in my iphone the issue persists. 

![image](https://cloud.githubusercontent.com/assets/1021901/19418454/91546ba2-939a-11e6-9740-74d1c3bf6a58.png)

**Comment by christocracy** [comment]
tns platform remove ios

Re add it

**Comment by marciovicente** [comment]
```
file:///app/tns_modules/nativescript-background-geolocation-lt/background-geolocation.js:376:53: JS ERROR ReferenceError: Can't find variable: TSLocationManager
Oct 16 16:35:33 Marcios-MacBook-Pro-2 com.apple.CoreSimulator.SimDevice.62A75B7E-B30D-449A-B77E-F7DE858C4547.launchd_sim[7398] (UIKitApplication:org.nativescript.smartdietTS[0xfc22][8543]): Service exited due to signal: Segmentation fault: 11
```

**Comment by christocracy** [comment]
I've refactored `BackgroundFetch` now.  Initiate a chat with me at http://www.transistorsoft.com and I'll walk you through it.
