### ISSUE TITLE
file:///app/main-view-model.js:3:55: JS ERROR Error: Could not find module 'nativescript-background-geolocation-lt'.

### ISSUE THREAD

**Issue by AndersGerner** [transistorsoft/nativescript-background-geolocation-lt#2]
When i try and run the demo app, I get the above error. Which i also do in all of the other apps i tried to use this plugin.

Can you help me? :)

(I added to error to the heading on purpose, in case anyone tries to Google a solution) :)

**Comment by christocracy** [comment]
It's not really a problem.  The demo app should run in spite of that

On Saturday, June 18, 2016, Anders Gerner <notifications@github.com> wrote:

> When i try and run the demo app, I get the above error. Which i also do in
> all of the other apps i tried to use this plugin.
>
> Can you help me? :)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/nativescript-background-geolocation-lt/issues/2>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6ly-pmuSSDcKwiluCXaJjv2n2fYcKks5qM-iOgaJpZM4I48KQ>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
Merged latest to master

**Comment by mounirka** [comment]
Hi @christocracy, i have the same issue mentioned by Anders, i can't figure out what is the problem. 
I tried to create a new app, i added the plugin from the CLI and when i import the plugin from the code, it says that it can't found the module.
Hope you can solve this. Thanks.

**Comment by christocracy** [comment]
Yea, I just tried to install from scratch here and it failed for me.  I'm working on it.

**Comment by christocracy** [comment]
Ok, try this after fetching latest from master here:
```Bash
$ cd nativescript-background-geolocation-lt
$ npm install
$ npm run setup

$ npm run demo.android
or
$ npm run demo.ios
```

**Comment by mounirka** [comment]
Thank you, now the demo is working.

**Comment by christocracy** [comment]
Super, thanks.  Let me know if you have any issues.
