### ISSUE TITLE
No sounds on Android

### ISSUE THREAD

**Issue by 3rror404** [transistorsoft/nativescript-background-geolocation-lt#21]
I don't get any audio notifications in debug mode on Android. This hasn't really been an issue until now but I'd like to use `#playSound` in my app. However, this also doesn't seem to be working.

iOS works fine.

```
var soundID = Platform.isIOS ? 1104 : 89;
BackgroundGeolocation.playSound(soundID);
```

**Comment by christocracy** [comment]
Are you sure you have configured `debug: true` for Android?  Volume turned on?

**Comment by 3rror404** [comment]
Yeah absolutely. It's more the #playSound not working when _not_ in debug mode that is an issue.
Does sound work for you in the ns demo app? I don't have a copy to test at the minute.

**Comment by christocracy** [comment]
I just set `debug: false` and `#playSound` still works.

**Comment by 3rror404** [comment]
OK thanks for testing. I can't find anything online that would suggest so but does audio on Android require any permissions that I might be missing? 

I'm going to pull the demo and see if I get the same behaviour with your setup.

**Comment by christocracy** [comment]
no permissions required

**Comment by christocracy** [comment]
See README of repo for changed setup instructions, particularly with `nativescript-background-fetch`

**Comment by 3rror404** [comment]
Turns out my "notification" volume was set to mute. Who knew there was four separate volume controls hidden in settings? Urgh Android.
