### ISSUE TITLE
Error executing "tns run ios"

### ISSUE THREAD

**Issue by dalmirof** [transistorsoft/nativescript-background-geolocation-lt#3]
Hello,
I am trying to execute the demo but I got this error:

nativescript-background-geolocation-lt@1.0.2 node_modules/nativescript-background-geolocation-lt
npm ERR! install trying to install 1.0.2 to /Users/dalmirof/Documents/nativescript_projects/nativescript-background-geolocation-lt/demo/node_modules/nativescript-background-geolocation-lt
npm ERR! install but already installed versions [ '1.0.2' ]
nativescript-background-geolocation-lt@1.0.2 node_modules/nativescript-background-geolocation-lt
Executing before-prepare hook from /Users/dalmirof/Documents/nativescript_projects/nativescript-background-geolocation-lt/demo/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 1.8.10
app/app.ts(4,3): error TS2304: Cannot find name 'GMSServices'.

app/main-view-model.ts(2,37): error TS2307: Cannot find module 'nativescript-background-geolocation-lt'.

Failed to find LaunchScreen.storyboard but it was specified in the Info.plist.
Consider updating the resources in app/App_Resources/iOS/.
A good starting point would be to create a new project and diff the changes with your current one.
Also the following repo may be helpful: https://github.com/NativeScript/template-hello-world/tree/master/App_Resources/iOS
We will now place an empty obsolete compatability white screen LauncScreen.xib for you in platforms/ios/demo/Resources/LaunchScreen.xib so your app may appear as it did in pre v2.1.0 versions of the ios runtime.
Successfully prepared plugin nativescript-background-geolocation-lt for ios.
Successfully prepared plugin nativescript-fonticon for ios.
Successfully prepared plugin nativescript-google-maps-sdk for ios.
Successfully prepared plugin tns-core-modules for ios.
Successfully prepared plugin tns-core-modules-widgets for ios.
Installing pods...
Analyzing dependencies
Fetching podspec for `nativescript-background-geolocation-lt` from `../../node_modules/nativescript-background-geolocation-lt/platforms/ios`
[!] The `nativescript-background-geolocation-lt` pod failed to validate due to 1 error:
    - WARN  | attributes: Missing required attribute `license`.
    - ERROR | attributes: Missing required attribute `source`.
    - WARN  | license: Missing license type.

Processing node_modules failed. Error: Command sandbox-pod failed with exit code 1

Any idea?
Best

Dalmiro

**Comment by christocracy** [comment]
I'll have a look.



On Tuesday, July 12, 2016, dalmirof <notifications@github.com> wrote:

> Hello,
> I am trying exceute the demo but I got this error:
>
> nativescript-background-geolocation-lt@1.0.2
> node_modules/nativescript-background-geolocation-lt
> npm ERR! install trying to install 1.0.2 to
> /Users/dalmirof/Documents/nativescript_projects/nativescript-background-geolocation-lt/demo/node_modules/nativescript-background-geolocation-lt
> npm ERR! install but already installed versions [ '1.0.2' ]
> nativescript-background-geolocation-lt@1.0.2
> node_modules/nativescript-background-geolocation-lt
> Executing before-prepare hook from
> /Users/dalmirof/Documents/nativescript_projects/nativescript-background-geolocation-lt/demo/hooks/before-prepare/nativescript-dev-typescript.js
> Found peer TypeScript 1.8.10
> app/app.ts(4,3): error TS2304: Cannot find name 'GMSServices'.
>
> app/main-view-model.ts(2,37): error TS2307: Cannot find module
> 'nativescript-background-geolocation-lt'.
>
> Failed to find LaunchScreen.storyboard but it was specified in the
> Info.plist.
> Consider updating the resources in app/App_Resources/iOS/.
> A good starting point would be to create a new project and diff the
> changes with your current one.
> Also the following repo may be helpful:
> https://github.com/NativeScript/template-hello-world/tree/master/App_Resources/iOS
> We will now place an empty obsolete compatability white screen
> LauncScreen.xib for you in platforms/ios/demo/Resources/LaunchScreen.xib so
> your app may appear as it did in pre v2.1.0 versions of the ios runtime.
> Successfully prepared plugin nativescript-background-geolocation-lt for
> ios.
> Successfully prepared plugin nativescript-fonticon for ios.
> Successfully prepared plugin nativescript-google-maps-sdk for ios.
> Successfully prepared plugin tns-core-modules for ios.
> Successfully prepared plugin tns-core-modules-widgets for ios.
> Installing pods...
> Analyzing dependencies
> Fetching podspec for nativescript-background-geolocation-lt from
> ../../node_modules/nativescript-background-geolocation-lt/platforms/ios
> [!] The nativescript-background-geolocation-lt pod failed to validate due
> to 1 error:
> - WARN | attributes: Missing required attribute license.
> - ERROR | attributes: Missing required attribute source.
> - WARN | license: Missing license type.
>
> Processing node_modules failed. Error: Command sandbox-pod failed with
> exit code 1
>
> Any idea?
> Best
>
> Dalmiro
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/transistorsoft/nativescript-background-geolocation-lt/issues/3>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l52eD6rdjskQx2zWucnLX6t0S7iQks5qVB9BgaJpZM4JK6sb>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
I've got Android nearly ready for release.  I'll need to take another pass at iOS now.

**Comment by christocracy** [comment]
Try with latest merged to master.

**Comment by christocracy** [comment]
See new demo instructions in README.  Should work now
