### ISSUE TITLE
Running demo

### ISSUE THREAD

**Issue by narayananl23** [transistorsoft/nativescript-background-geolocation-lt#30]
Demo Build was successful. I have all the sdk tool and packages. I was able to get https://github.com/dapriett/nativescript-google-maps-sdk and location of nativescript working on my SDK and on my emulator. I am using api 25 , running in windows.

the error when demo gets loaded on the device..

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.transistorsoft.backgroundgeolocation.nativescript/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onStart failed

TypeError: Cannot read property 'getInstance' of undefined
File: "/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/frame/frame.js, line: 702, column: 18

StackTrace: 
	Frame: function:'BackgroundGeolocation.onGooglePlayServicesConnectError', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/nativescript-background-geolocation-lt/background-geolocation.js', line: 418, column: 82
	Frame: function:'BackgroundGeolocation.init', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/nativescript-background-geolocation-lt/background-geolocation.js', line: 36, column: 27
	Frame: function:'BackgroundGeolocation.onActivityStarted', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/nativescript-background-geolocation-lt/background-geolocation.js', line: 21, column: 14
	Frame: function:'', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/nativescript-background-geolocation-lt/background-geolocation.js', line: 13, column: 27
	Frame: function:'Observable.notify', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/data/observable/observable.js', line: 149, column: 23
	Frame: function:'android.app.Application.ActivityLifecycleCallbacks.onActivityStarted', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/application/application.js', line: 78, column: 24
	Frame: function:'ActivityCallbacksImplementation.onStart', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/frame/frame.js', line: 702, column: 19
	Frame: function:'NativeScriptActivity.onStart', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/frame/activity.js', line: 18, column: 25

	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

thanks

**Comment by christocracy** [comment]
Try the latest version posted yesterday

**Comment by narayananl23** [comment]
I did try now using the latest
$ git clone https://github.com/transistorsoft/nativescript-background-geolocation-lt.git
$ cd nativescript-background-geolocation-lt
$ npm install
$ tsc

$ npm run setup
$ npm run demo.android

Same error.

**Comment by narayananl23** [comment]
I also went and strip down to as simple as possible.  No build issue and the same error on the emulator  when the app loads on an emulator. Here is the code.

I also tried adding this to app.gradle 
project.ext {
    googlePlayServicesVersion = "9.6.0+"
}

[main-page.ts.txt](https://github.com/transistorsoft/nativescript-background-geolocation-lt/files/567100/main-page.ts.txt)
[main-page.xml.txt](https://github.com/transistorsoft/nativescript-background-geolocation-lt/files/567102/main-page.xml.txt)
[main-view-model.ts.txt](https://github.com/transistorsoft/nativescript-background-geolocation-lt/files/567101/main-view-model.ts.txt)

Thanks

**Comment by loadchief** [comment]
NativeScript 2.5.4
Android 5.1.0

```
Executing before-watch hook from C:\Code\BTDemo\demo\hooks\before-watch\nativescript-dev-typescript.js
Found peer TypeScript 2.2.2
JS: EXCEPTION: Error in :0:0 caused by: Cannot read property 'getInstance' of undefined
JS: ORIGINAL EXCEPTION: Cannot read property 'getInstance' of undefined
JS: ORIGINAL STACKTRACE:
JS: TypeError: Cannot read property 'getInstance' of undefined
JS:     at Function.BackgroundGeolocation.onGooglePlayServicesConnectError (file:///data/data/org.nativescript.lcmobile/files/app/tns_modules/nativescript-back
ground-geolocation-lt/background-geolocation.js:432:82)
JS:     at Function.BackgroundGeolocation.init (file:///data/data/org.nativescript.lcmobile/files/app/tns_modules/nativescript-background-geolocation-lt/backgr
ound-geolocation.js:444:27)
JS:     at Function.BackgroundGeolocation.getAdapter (file:///data/data/org.nativescript.lcmobile/files/app/tns_modules/nativescript-background-geolocation-lt/
background-geolocation.js:451:18)
JS:     at Function.BackgroundGeolocation.setConfig (file:///data/data/org.nativescript.lcmobile/files/app/tns_modules/nativescript-background-geolocation-lt/b
ackground-geolocation.js:82:14)
JS:     at new AppComponent (file:///data/data/org.nativescript.lcmobile/files/app/app.component.js:7:72)
JS:     at new Wrapper_AppComponent (/AppModule/AppComponent/wrapper.ngfactory.js:7:18)
JS:     at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.createInternal (/AppModule/AppComponent/host.ngfactory.js:15:28)
JS:     at CompiledTemplate.proxyViewClass.AppView.createHostView (file:///data/data/org.nativescript.lcmobile/files/app/tns_modules/@angular/core/bundles/core
.umd.js:12266:25)
JS:     at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (file:///data/data/org.nativescript.lcmobile/files/app/tns_modules/@angular/core/bundles
/core.umd.js:12674:56)
JS:     at ComponentFactory.create (file:///data/data/org.nativescript.lcmobile/files/app/tns_modules/@angular/core/bundles/core.umd.js:7690:29)
JS: ERROR CONTEXT:
JS: [object Object]
JS: ns-renderer: ERROR BOOTSTRAPPING ANGULAR
JS: ns-renderer: Error in :0:0 caused by: Cannot read property 'getInstance' of undefined
```

**Comment by christocracy** [comment]
Are you running this on a device or simulator?

**Comment by loadchief** [comment]
yes, Gennymotion

**Comment by christocracy** [comment]
With play-services installed?

**Comment by loadchief** [comment]
yes, we did install google play-services via the sdk manager

**Comment by loadchief** [comment]
we also made this adjustment in Gennymotion:

![image](https://cloud.githubusercontent.com/assets/20728482/25032082/36cfb410-2086-11e7-8e4e-2bf116d6d8da.png)

**Comment by loadchief** [comment]
I can share my screen with you via team viewer if that would help

**Comment by christocracy** [comment]
No, I found [the issue](https://github.com/transistorsoft/nativescript-background-geolocation-lt/blob/master/background-geolocation.android.ts#L480).  This code doesn't execute often.

It's referencing `com.google.android.gms.common.GoogleApiAvailability.GoogleApiAvailability...`

Should be just `com.google.android.gms.common.GoogleApiAvailability...`

**Comment by christocracy** [comment]
Install latest from master.  Note [the instructions](https://github.com/transistorsoft/nativescript-background-geolocation-lt#from-master-latest-greatest) for building from master:  you must clone the repo, compile the typescript (to generate the plugin's .js files) then `npm install /path/to/cloned/repo`

**Comment by loadchief** [comment]
ok, thank you.  will give this a try...

**Comment by nraboy** [comment]
@christocracy,

Per your instructions, the `master` branch no longer receives the `getInstance` error, however the demo application appears to be plagued with other errors.  So a few questions:

1. When will the `master` branch make it into a version on NPM?
2. Have you tested all features of the demo recently?

I also noticed that there are a ton of TypeScript errors when using the plugin.

Best,

**Comment by christocracy** [comment]
What other errors?

Don't worry about Typescript errors.

**Comment by nraboy** [comment]
I get this when I click the location button:

```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onClick failed

Error: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Boolean com.transistorsoft.locationmanager.location.TSLocationManager.isLocationServicesEnabled()' on a null object reference
    com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getCurrentPosition(Unknown Source)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
    com.tns.Runtime.callJSMethod(Runtime.java:1047)
    com.tns.Runtime.callJSMethod(Runtime.java:1028)
    com.tns.Runtime.callJSMethod(Runtime.java:1018)
    com.tns.gen.android.view.View_OnClickListener.onClick(android.view.View$OnClickListener.java)
    android.view.View.performClick(View.java:5198)
    android.view.View$PerformClick.run(View.java:21147)
    android.os.Handler.handleCallback(Handler.java:739)
```

I get this when I restart the application:

```
04-14 11:42:20.900  2179  2179 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.transistorsoft.backgroundgeolocation.nativescript/com.tns.NativeScriptActivity}: java.lang.NullPointerException: Attempt to read from field 'int com.tns.Runtime.currentObjectId' on a null object reference
04-14 11:42:20.900  2179  2179 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2327)
04-14 11:42:20.900  2179  2179 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
04-14 11:42:20.900  2179  2179 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
04-14 11:42:20.900  2179  2179 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
04-14 11:42:20.900  2179  2179 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-14 11:42:20.900  2179  2179 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
04-14 11:42:20.900  2179  2179 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
04-14 11:42:20.900  2179  2179 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-14 11:42:20.900  2179  2179 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-14 11:42:20.900  2179  2179 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

I realize the TypeScript errors don't affect the outcome of the build, but it would be nice if they were corrected.

Best,

**Comment by christocracy** [comment]
@nraboy Are you running this on a device or sim?  I cannot duplicate that error running the demo on my devices.

**Comment by nraboy** [comment]
I am using Genymotion.  I realize you need location services available, but there should also be more graceful exceptions being thrown within the application if these are truly related to the location services.

It may be unrelated, but the standard NativeScript geolocation plugin works fine in my Genymotion.

**Comment by christocracy** [comment]
It's not about whether location services is available, it's about the object *that asks whether location services is available* is present.

```
transistorsoft.locationmanager.location.TSLocationManager.isLocationServicesEnabled()
```

**Comment by nraboy** [comment]
It is your demo application, so I would assume it has this line.

**Comment by christocracy** [comment]
Can you try booting on a real device?

**Comment by christocracy** [comment]
There's something missing in your Genymotion sim.

**Comment by loadchief** [comment]
I cloned master, and ran npm and tsc.  but when I try to do a tns build android I get:

PS C:\Code\temp\btdemo\demo> tns build android
npm ERR! addLocal Could not install C:\Users\chris\Documents\workspace\NativeScript\background-geolocation\nativescript-background-geolocation-lt
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! path C:\Users\chris\Documents\workspace\NativeScript\background-geolocation\nativescript-background-geolocation-lt
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\chris\Documents\workspace\NativeScript\background-geolocation\nativescript-background-geoloca
tion-lt'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\chris\Documents\workspace\NativeScript\background-geolocation\nativescript-background-geoloca
tion-lt'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Code\temp\btdemo\demo\npm-debug.log
Unable to install dependencies. Make sure your package.json is valid and all dependencies are correct. Error is: Command npm.cmd failed with exit code 42949632
38

**Comment by nraboy** [comment]
@loadchief in your **package.json** file, remove the already existing `nativescript-background-geolocation-lt` plugin.  It is currently set to @christocracy home directory.  Removing and readding it should work.

**Comment by loadchief** [comment]
I replaced with this and seems to work, but will just try removing it too

"nativescript-background-geolocation-lt": "file://code/code/temp/btdemo/",

**Comment by christocracy** [comment]
Thanks @nraboy.  It shouldn't have been committed like that.  It's supposed to reference : "../".

Fixed in master.  Pull to get changes.

**Comment by christocracy** [comment]
To build the demo app from master, just do this:
```
$ git clone https://github.com/transistorsoft/nativescript-background-geolocation-lt.git
$ cd nativescript-background-geolocation-lt
$ npm install
$ npm run demo.android
```

**Comment by loadchief** [comment]
have not had a chance to play with it yet but the demo does open and finds my current location, thanks!

**Comment by christocracy** [comment]
The Android relies on an accelerometer-based motion-detection API from play-services.  Sims doing have accelerometers so it's not easy to fully test the plugin in a simulated environment.

**Comment by loadchief** [comment]
no worries, I will leave the sim out and just test on android device

**Comment by christocracy** [comment]
I have 10 devices on my desk.  My primary development devices are:
```
- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Nexus 6 @ 6.0.1
- Pixel @ 7.1.1
```

**Comment by loadchief** [comment]
Hi Chris, any eta on versioning master branch in npm?

**Comment by christocracy** [comment]
I have updated binaries for both Android and iOS to bring over from work on Cordova / React Native.  Probably next week.

**Comment by loadchief** [comment]
We are able to get an initial console dump that shows my location on my device, then my phone beeps in debug mode every 1 min or so but we don't get subsequent dumps of location data?  Any thoughts please?

`export class AppComponent implements OnInit  { 

    public ngOnInit() {
        
        BackgroundGeolocation.on("location", this.onLocation);
        
        BackgroundGeolocation.configure({ 
            debug: true,           
            desiredAccuracy: 0,
            distanceFilter: 20, 
            locationUpdateInterval: 5000,
            fastestLocationUpdateInterval: 1000,
            deferTime: 0,
            locationTimeout: 60,            
            stopTimeout: 1,
            heartbeatInterval: 60,
            logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
            activityRecognitionInterval: 1000,
            }, function(state) {
                console.log('NEW background geoloaction ready...')
                BackgroundGeolocation.start();
        }, function() {
                console.log('error');
        })
    }

    public constructor() { 
    }

    public onLocation(location: any) {
        console.dump(location);
    }    
   
}`

**Comment by christocracy** [comment]
Must be some wronf with your console.dump

-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
If you have unrelated issues to this topic, please open a new issue
