### ISSUE TITLE
onHTTP and onHTTPError return different types

### ISSUE THREAD

**Issue by 3rror404** [transistorsoft/nativescript-background-geolocation-lt#36]
Hi Chris,

The `onHTTP` event returns an object and `onHTTPError` returns JSON. 

If there is no particular reason for this, could they both return the same type? An object would be preferable to me.

Not urgent.

**Comment by christocracy** [comment]
Fix coming soon.

**Comment by christocracy** [comment]
Try out the branch [setOdometer](https://github.com/transistorsoft/nativescript-background-geolocation-lt/pull/37)

**Comment by 3rror404** [comment]
Hi Chris,

Using `master`, a 403 status triggers the `onHTTPError` but using the `setOdometer` branch a 403 triggers `onHTTP`. Was this intentional? `onHTTPError` would seem more logical to me for anything other than 20x.

Or is `onHTTPError` intended for network issue?

Thanks

**Comment by christocracy** [comment]
[Good catch](https://github.com/transistorsoft/nativescript-background-geolocation-lt/blob/setOdometer/background-geolocation.android.ts#L435)

```Javascript
private static createHttpCallback(success:Function, failure?:Function) {
    failure = failure || emptyFn;
    return new Callback({
      success: function(response) {
        success(JSON.parse(response.toString()));
      },
      error: function(response) {
        failure(JSON.parse(response.toString()));  // <-- Should have called the `failure` callback.
      }
    });
  }
```

**Comment by christocracy** [comment]
Pushed to `setOdometer` branch.

**Comment by 3rror404** [comment]
Perfect. Thanks
