### ISSUE TITLE
Android plugin starts before. start function is called.

### ISSUE THREAD

**Issue by narayananl23** [transistorsoft/nativescript-background-geolocation-lt#39]
In android, it starts before start method is called. Here is the code.

`

        constructor() {
        super();
        //if (this._state) { return };
        BackgroundGeolocation.on("location", this.onLocation.bind(this));
        // Configure it.
        BackgroundGeolocation.configure({
            debug: false,
            desiredAccuracy: 10,
            stationaryRadius: 25,
            distanceFilter: 20,
            activityRecognitionInterval: 10000,
            isMoving: true,
            license: "*********************************"
        }, function (state) {
            this._state = state;
        }.bind(this));

    }`

here is the method called by an onTap envent

`
    public onStartTap() {
        BackgroundGeolocation.start(function () { });
    }
`

**Comment by christocracy** [comment]
This is not an issue, it's a feature.  The plugin *remembers* its `enabled` state between restarts / reboots.

```Javascript
BackgroundGeolocation.configure(config, function(state) {
  console.log('- Configure success.  Enabled? ', state.enabled);
});
```

**Comment by narayananl23** [comment]
I see. then in my use case i should not have it in constructor.  This one works the way I want. I do not know if on restart this will work.


    constructor() {
        super();
        if (this._state) { return };
        BackgroundGeolocation.on("location", this.onLocation.bind(this));
    }

```
public onStartTab() {
         // Configure it.
        BackgroundGeolocation.configure({
            debug: false,
            desiredAccuracy: 10,
            stationaryRadius: 25,
            distanceFilter: 20,
            activityRecognitionInterval: 10000,
            isMoving: true,
            license: "***************"
        }, function (state) {
            console.log('- Configure success.  Enabled? ', state.enabled);
            BackgroundGeolocation.start(function () { });
            this._state = state;
        }.bind(this));
    } 
```
