### ISSUE TITLE
icon like demo - question

### ISSUE THREAD

**Issue by narayananl23** [transistorsoft/nativescript-background-geolocation-lt#40]
How can I get an notification bar icon like the nativescript-background-geolocation-lt  demo. I would like the icon to show only when the app goes to background ?

Thanks,

**Comment by christocracy** [comment]
What icon?

**Comment by narayananl23** [comment]
The one on the top left corner of the attachted photo.

Thanks
Narayan

**Comment by christocracy** [comment]
What attached photo?  You can't attach a photo to a github issue from an email.

**Comment by narayananl23** [comment]
![img_20161204_174059](https://cloud.githubusercontent.com/assets/3720723/20871381/fafc23da-ba49-11e6-9ec1-146e102d26ed.jpg)

I figured out. Thanks for letting me know. 

Narayan

**Comment by christocracy** [comment]
No, you cannot selectively show/hide that icon.  That icon is **required** by the Android OS when you configure `foregroundService: true`.  This mode makes the plugin's background-service *mostly* immune to the OS terminating the tracking service due to memory pressure.

That icon is show when the plugin is `#start`ed.

**Comment by christocracy** [comment]
For more information on `foregroundService`, see Android Service docs:
https://developer.android.com/reference/android/app/Service.html#startForeground(int, android.app.Notification)

>Make this service run in the foreground, **supplying the ongoing notification to be shown to the user while in this state**. By default services are background, meaning that if the system needs to kill them to reclaim more memory (such as to display a large page in a web browser), they can be killed without too much harm. **You can set this flag if killing your service would be disruptive to the user**, such as if your service is performing background music playback, so the user would notice if their music stopped playing.

**Comment by narayananl23** [comment]
Ok. Thanks

Narayan
