### ISSUE TITLE
TSLocationManager framework: No such file or directory

### ISSUE THREAD

**Issue by narayananl23** [transistorsoft/nativescript-background-geolocation-lt#43]
## Your Environment
* Plugin version: 1.3.2
* Platform: iOS or Android - both
* OS version: IOS latest
* Device manufacturer / model Mac:
* Nativescript version (`tns info`):
Component        │ Current version       │ Latest version │ Information      │
│ nativescript     │ 2.4.0                 │ 2.4.1          │ Update available │
│ tns-core-modules │ 2.5.0-2016-11-23-4850 │ 2.4.2          │ Up to date       │
│ tns-android      │ 2.4.1                 │ 2.4.1          │ Up to date       │
│ tns-ios          │ 2.4.0                 │ 2.4.0          │ Up to date
* Plugin config

## Steps to Reproduce

1.tns plugin remove nativescript-background-geolocation-lt
2.
3.
4.

## Debug logs

> 
rm -r ../../lib/iOS/TSLocationManager.framework

rm: ../../lib/iOS/TSLocationManager.framework: No such file or directory
unbuild nativescript-background-geolocation-lt@1.3.2
npm WARN continuing anyway nativescript-background-geolocation-lt@1.3.2 uninstall: `rm -r ../../lib/iOS/TSLocationManager.framework
`
npm WARN continuing anyway Exit status 1

**Comment by christocracy** [comment]
Ignore this.  This needs to remove its binaries from the app when your remove the plugin in order to guarantee the latest binaries are installed when remove/add the plugin.  If the platform doesn't exist, those binaries obviously won't exist, thus "No such file or directory".

**Comment by narayananl23** [comment]
ok. Thanks
