### ISSUE TITLE
google play services - Android question

### ISSUE THREAD

**Issue by narayananl23** [transistorsoft/nativescript-background-geolocation-lt#45]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Nativescript version (`tns info`):
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

Frequently I run into issues with play services while testing.  in windows and also in ios.  The plugin relies on play services.  to avoid missing google play services, is it good to add it to the android  manifest like.

google_play_services_version

```
<meta-data android:name="com.google.android.gms.version"
    android:value="@integer/google_play_services_version" />
```

**Comment by christocracy** [comment]
What sort of issue?

**Comment by narayananl23** [comment]
Plugin does not  start and fails at getinstance null.

**Comment by christocracy** [comment]
The issue-template asked you for a bunch of information that you ignored

*****************************************************************
* WARNING:  If you ignore this template, your issue will be too.
*****************************************************************
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Nativescript version (`tns info`):
* Plugin config

**Comment by narayananl23** [comment]
Plugin version: 1.3.1,1.3.2,1.3.3
Platform: iOS or Android : Android only
OS version: Windows 7 or IOS latest
Device manufacturer / model: simulator
Nativescript version (tns info): 2.4.0,2.4.1,2.4.2
Plugin config

It is the config of google AVD that is why i did not post those details. 

```

BackgroundGeolocation.configure({
                debug: true,
                desiredAccuracy: 0,
                stationaryRadius: 25,
                distanceFilter: 20,
                activityRecognitionInterval: 10000,
                locationUpdateInterval: 5000,
                stopTimeout: 5,
                isMoving: true,
                license: "*******"
            }, function (state) {
                viewModel._state = state;
                if (!viewModel._state.enabled) {
                    BackgroundGeolocation.start(function () { });
                }
                console.log('- Configure success.  Enabled? ', state.enabled);
            }.bind(this));
        }



```
It fails here in the plugin..

```
    BackgroundGeolocation.init = function () {
        this.intent = app.android.foregroundActivity.getIntent();
        this.getAdapter().on("playservicesconnecterror", new Callback({
            success: this.onGooglePlayServicesConnectError.bind(this),
            error: emptyFn
        }));
    };
```

If the plugin works even if play service is not enabled that will make sure it works on many platform.

**Comment by christocracy** [comment]
If the plugin were a car, Google Play-Services is the engine.  The plugin *requires* play-services.

**Comment by narayananl23** [comment]
does All devices run android have Google Play-Services ?

**Comment by christocracy** [comment]
Pretty much, unless you live in China.

**Comment by narayananl23** [comment]
ok.Thanks 

Please see the screenshot. I am using the latest 

nativescript     │ 2.4.2           │ 2.4.2          │ Up to date  │
│ tns-core-modules │ 2.4.2           │ 2.4.2          │ Up to date  │
│ tns-android      │ 2.4.1           │ 2.4.1          │ Up to date  │
│ tns-ios          │ 2.4.0           │ 2.4.0          │ Up to date

![screenshot_1481218072](https://cloud.githubusercontent.com/assets/3720723/21020318/dbb30566-bd28-11e6-80be-192949fdd30a.png)
![screenshot_1481218152](https://cloud.githubusercontent.com/assets/3720723/21020319/dbb3ae44-bd28-11e6-9222-3f56358a4797.png)

**Comment by narayananl23** [comment]
It is to do with android device configuration or your initial setup of nativescript, permission and android sdk. The best approach for others is try the demo app and if it works.. then your android emulator is good. Try a fresh directory/instance with demo. While troubleshooting to make it work, we make lot of changes and it could also cause some issue. What I have seen is Nativescript is fragile.
