### ISSUE TITLE
Location event triggered on resetOdometer

### ISSUE THREAD

**Issue by narayananl23** [transistorsoft/nativescript-background-geolocation-lt#46]
## Your Environment
* Plugin version: 1.3.3
* Platform:  Tested only in android 
* OS version: Mac latest
* Device manufacturer / model: 
* Nativescript version (`tns info`):
 Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.4.2           │ 2.4.2          │ Up to date    │
│ tns-core-modules │ 2.4.2           │ 2.4.2          │ Up to date    │
│ tns-android      │ 2.4.1           │ 2.4.1          │ Up to date
* Plugin config
 BackgroundGeolocation.configure({
                debug: true,
                desiredAccuracy: 0,
                stationaryRadius: 25,
                distanceFilter: 20,
                activityRecognitionInterval: 10000,
                locationUpdateInterval: 1000,
                stopTimeout: 5,
                isMoving: true,
                changePace: true, //<-- for testing Aggressive GPS monitoring immediately engaged. to suport testing on device
               license: ""

## Actual Behavior
When i call BackgroundGeolocation.resetOdometer, location on event is getting triggered.

console output
```
JS: - cleared Odometer
JS: true,2016-12-10T16:04:00.000Z,f4c4ac15-33e5-45f8-a58f-da9fb2f8d31d,50.4609,8.48924
```

## Steps to Reproduce
  reproduce this issue; include code to reproduce, if relevant 
```
  public clearTap() {
        BackgroundGeolocation.resetOdometer(function () {
            console.log('- cleared Odometer');
        });
    public onLocation(location: any) {
        console.log(location.is_moving + "," + location.timestamp + "," + location.uuid + "," + location.coords.latitude + "," + location.coords.longitude);
    }

```

**Comment by christocracy** [comment]
This is by design.  See the docs.  In order for the odometer calculator to work properly, it needs to know the exact location where odometer was modified.
