### ISSUE TITLE
[TSDBLogger db_save] Log committed keep printing

### ISSUE THREAD

**Issue by narayananl23** [transistorsoft/nativescript-background-geolocation-lt#48]
What is this ? "[TSDBLogger db_save] Log committed" can that be stoped ? Not urgent, low priority question. 

## Your Environment
* Plugin version: 1.3.3
* Platform:  iPhone 6 iOS 10.1, iPhone 7 IOS 10.1
* OS version: Mac latest
* Device manufacturer / model: iPhone simulator
* Nativescript version (`tns info`):
 Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.4.2           │ 2.4.2          │ Up to date    │
│ tns-core-modules │ 2.4.2           │ 2.4.2          │ Up to date    │
│ tns-android      │ 2.4.1           │ 2.4.1          │ Up to date
│tns-ios          │ 2.4.0           │ 2.4.0          │ Up to date

* Plugin config
```
nativescript_background_geolocation_lt_1.BackgroundGeolocation.configure({
                debug: false,
                desiredAccuracy: 10,
                stationaryRadius: 25,
                distanceFilter: 20,
                activityRecognitionInterval: 5000
            
```
## Steps to Reproduce

1. Start 
2. Stop the plugin
3.
4.

## Debug logs
🔴-[SOMotionDetector stopShakeDetection] OFF
🔴-[TSLocationManager stopUpdatingLocation]
- TSBackgroundFetch removeListener: TSLocationManager
🔴-[TSLocationManager stop] Stop monitoring significant-changes
🔴-[TSLocationManager stopMonitoringBackgroundFetch] BackgroundFetch: OFF
CONSOLE INFO file:///app/main-view-model.ts:102:21: off
CONSOLE LOG file:///app/main-view-model.ts:24:24: - count:  12
⋯-[TSDBLogger db_save] Log committed
🔵-[TSLocationManager setOdometer:success:failure:]
🔵-[Settings setOdometer:] 0
CONSOLE LOG file:///app/main-view-model.ts:31:24: - cleared Odometer
ℹ️__20-[LocationDAO clear]_block_invoke Destroyed all locations
CONSOLE LOG file:///app/main-view-model.ts:34:24: - cleared database
CONSOLE LOG file:///app/main-view-model.ts:36:21: - clear tap done
⋯-[TSDBLogger db_delete] maxAge: 604800
⋯-[TSDBLogger db_save] Log committed
⋯-[TSDBLogger db_save] Log committed
⋯-[TSDBLogger db_save] Log committed
⋯-[TSDBLogger db_save] Log committed
⋯-[TSDBLogger db_save] Log committed
⋯-[TSDBLogger db_delete] maxAge: 604800
⋯-[TSDBLogger db_save] Log committed
⋯-[TSDBLogger db_save] Log committed
⋯-[TSDBLogger db_save] Log committed
⋯-[TSDBLogger db_save] Log committed
⋯-[TSDBLogger db_save] Log committed
⋯-[TSDBLogger db_delete] maxAge: 604800
⋯-[TSDBLogger db_save] Log committed
⋯-[TSDBLogger db_save] Log committed

**Comment by christocracy** [comment]
Ignore it.  The iOS database logger is smart:  it holds log entries in memory, committing them to the database periodically, rather than doing an insert for each log entry
