### ISSUE TITLE
register the "location on" event only once 

### ISSUE THREAD

**Issue by narayananl23** [transistorsoft/nativescript-background-geolocation-lt#49]
General question, so I am not filling the template.

How can I only call this once ? 

 ```
   constructor() {
        super();
        if (this._state) { return };
         BackgroundGeolocation.on("location", this.onLocation.bind(this));
    }
```

I using the side drawer, when ever the page is loaded, It registers the location. If location is already registered, I do not want to register the "location on" event. 

Is there a way I can find if the event is register or not, then I can skip register.

Thanks,

**Comment by christocracy** [comment]
The easiest thing to do is keep track of this in your own app's state.

**Comment by narayananl23** [comment]
I was thinking about that. thanks

Is there a way I can ready the state and see if that is already enabled or not ?

Thanks,
Narayan

**Comment by christocracy** [comment]
[`getState`](https://github.com/transistorsoft/nativescript-background-geolocation-lt/tree/master/docs#getstatesuccessfn)
