### ISSUE TITLE
Advice on configuration to minimise gaps

### ISSUE THREAD

**Issue by 3rror404** [transistorsoft/nativescript-background-geolocation-lt#50]
## Your Environment
* Plugin version: 1.3.2
* Platform: Android (maybe iOS too)
* OS version: 6.0.1 (maybe other versions too)
* Device manufacturer / model: Samsung J5 (2016)
* Nativescript version (`tns info`):
```
┌──────────────────┬─────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 2.4.0           │ 2.4.2          │ Update available │
│ tns-core-modules │ 2.4.0           │ 2.4.2          │ Update available │
│ tns-android      │ 2.4.1           │ 2.4.1          │ Up to date       │
│ tns-ios          │ 2.4.0           │ 2.4.0          │ Up to date       │
└──────────────────┴─────────────────┴────────────────┴──────────────────┘
```
* Plugin config

```
    config = {
            license: "***",
            params: {
                device: {
                    platform: Platform.device.os,
                    manufacturer: Platform.device.manufacturer,
                    model: Platform.device.model,
                    version: Platform.device.osVersion,
                    uuid: Platform.device.uuid
                }
            },
            // Geolocation config
            desiredAccuracy: 0,
            distanceFilter: 20,
            stationaryRadius: 50,
            locationUpdateInterval: 5000,
            fastestLocationUpdateInterval: 5000,
            disableElasticity: false,

            // Activity Recognition config
            activityType: 'AutomotiveNavigation',
            activityRecognitionInterval: 5000,
            stopTimeout: 10,
            minimumActivityRecognitionConfidence: 75,

            // Application config
            debug: false,
            stopOnTerminate: true,
            preventSuspend: false,
            heartbeatInterval: 60,

            // Server sync
            autoSync: false,
            batchSync: true,
            maxBatchSize: -1,
            url : appConfig.apiUrl + 'journeyevent_v2/?token=' + Settings.getString("token"),
            extras : {
                journeyID: journeyID || 0,
                vehicleID: vehicleID
            }
            
        };
```

![app-tracking](https://cloud.githubusercontent.com/assets/1102402/21223696/7cef0fb4-c2c0-11e6-9de5-136c4f7c142b.jpg)

![app-tracking-locations](https://cloud.githubusercontent.com/assets/1102402/21223950/be78f908-c2c1-11e6-913c-02176e2be81d.jpg)

A user today stopped at a service station whilst tracking. They kept the app running and their walk around the store was recorded. However, at some point the app stopped tracking and didn't restart until they had returned to their vehicle and travelled 20+ miles (17 minutes). 

I understand the plugin wishes to switch of the GPS if the device is not moving but accuracy of mileage is vital for my app and a 20+ mile gap in tracking is going to cause major problems. Even a 1 mile gap will mean vital information is lost. Especially in an urban environment with lots of turns. 

If the plugin is `#start`ed I never want it to stop tracking until `#stop` is called.

Is there any way I can configure the plugin to _never stop_ even if it thinks the device is not moving?

I have no way to get logs from this device.

**Comment by christocracy** [comment]
`disableStopDetection: true`.

There's no way to speculate on what happened without logs.

[Here's two weeks around Iceland](http://www.transistorsoft.com/lab/iceland)

**Comment by 3rror404** [comment]
Yeah I've seen the Iceland trip. It also contains some anomalies

![iceland](https://cloud.githubusercontent.com/assets/1102402/21226970/d146a842-c2cf-11e6-91bb-66afd295f09f.jpg)

Do you think it is going to be possible to implement `#emailLog` in the NS version? It's currently very difficult if not impossible to get logs from my non-techy testers.

**Comment by christocracy** [comment]
Android lost of a day of data when I synced to the wrong server.  Not a tracking anomaly.

Over a period of 2 weeks on a remote island, this is behaviour you can expect.  You will get no better than this.

**Comment by 3rror404** [comment]
## Your Environment
* Plugin version: 1.5.0
* Platform: iOS
* OS version: 10.3.1
* Device manufacturer / model: Apple iPhone SE
* Nativescript version (`tns info`): 2.5

```
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 2.5.4           │ 2.5.4          │ Up to date  │
│ tns-core-modules │ 2.5.2           │ 2.5.2          │ Up to date  │
│ tns-android      │ 2.5.0           │ 2.5.0          │ Up to date  │
│ tns-ios          │ 2.5.0           │ 2.5.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘
```

* Plugin config

            // Geolocation config
            desiredAccuracy: 0,
            distanceFilter: 20,
            stationaryRadius: 50,
            locationUpdateInterval: 5000,
            fastestLocationUpdateInterval: 5000,
            disableElasticity: false,

            // Activity Recognition config
            activityType: 'AutomotiveNavigation',
            activityRecognitionInterval: 5000,
            disableStopDetection: true,
            stopTimeout: 10, // n/a if disableStopDetection: true
            minimumActivityRecognitionConfidence: 75,

            // Application config
            debug: false,
            stopOnTerminate: false,
            heartbeatInterval: 60,
            logLevel: 5,
            logMaxDays: 1,

            foregroundService: true, // Android

            // Server sync
            autoSync: false,
            batchSync: true,
            maxBatchSize: -1

I've finally managed to get a log from this user (https://gist.github.com/3rror404/c324f3e4b4ebe0306ae8d9bec6445f7f). Looking at the logs for today it looks like the gaps occur after the user has stopped for some time even when setting `disableStopDetection: true`.

Is there anything I can do to prevent this?

![jt-issue-andrew-map](https://cloud.githubusercontent.com/assets/1102402/25635004/9271e91c-2f74-11e7-8b24-e59f6fe37199.jpg)

![jt-issue-andrew-db](https://cloud.githubusercontent.com/assets/1102402/25635009/96ae0812-2f74-11e7-95a4-3bb33fbd9542.jpg)

**Comment by christocracy** [comment]
disableStopDetection does not prevent iOS from entering stationary mode after the device stops for stopTimeout minutes (in your case 10 minutes).

Once iOS does enter stationary mode, it will only be reawakened by exiting the stationary geofence it's asleep within.  This stationary geofence exit is completely dependent upon the os and the local network environment (e.g. Proximity of cell towers).  In my experience, this is typically ~200 meters in urban environments.

**Comment by 3rror404** [comment]
The [docs](https://github.com/transistorsoft/nativescript-background-geolocation-lt/blob/master/docs/README.md#config-boolean-disablestopdetection-false) confused me here as it says...

> When disabled, you will no longer have control over #stopTimeout.

I assumed that the timeout was unused if using `disableStopDetection`. But does this actually mean that the default 15 minutes will be used?

I guess I can't just set a huge `stopTimeout` and `disableStopDetection`?

**Comment by christocracy** [comment]
disableStopDetection does not disable stopTimeout.  disableStopDetection merely prevents the plugin from temporarily turning off location services when briefly stopped (to conserve energy), when stopped at a traffic light, for example.

I suggest you not disableStopDetection and either increase your stopTimeout (e.g. 30min) or keep stopTimeout low (eg 5-10) and use preventSuspend.  preventSuspend will prevent iOS from suspending your app while in stationary mode and continue listening to the motion-detection hardware.  You'll not want to engage preventSuspend 24/7.  You want to try and find a way to only engage it only when required (e.g. when a "trip" starts and turn it off when you know a "trip" is complete.

**Comment by christocracy** [comment]
Yes, the docs for that could be improved.  What that should mention is that the default iOS stop-detection algorithm will take over, which is typically 15min.

**Comment by christocracy** [comment]
However, the docs do say:

>Disables the accelerometer-based Stop-detection System. When disabled, the plugin will use the default iOS behaviour of automatically turning off location-services when the device has stopped for exactly 15 minutes. When disabled, you will no longer have control over

**Comment by 3rror404** [comment]
OK thanks for the suggestions. I always use `start`/`stop` at the beginning and end of a trip so I can config `preventSuspend` no problem.

What is the reason to use a low `stopTimeout` with `preventSuspend`? Is this just for battery saving? Accuracy is more important to me than battery life. Would it be insane to use a stopTimeout of 60mins along with preventSuspend do you think?

**Comment by christocracy** [comment]
Because with preventSuspend, your app is constantly alive in the background, monitoring the motion-detection hardware.  It will rapidly detect movement and engage tracking.

It can be helpful to have a low stopTimeout so you can analyze the data for motionchange events and say "ok, stopped here for x minutes".  With a too high stopTimeout, you'd never be able to determine significant stops (e.g. Gas station, stop for lunch, etc).

Even a stopTimeout: 0 will work perfectly fine with preventSuspend.  Note also that your JavaScript is alive and running as long as preventSuspend: true

**Comment by 3rror404** [comment]
That makes sense. Thanks a lot for the help  👍
