### ISSUE TITLE
Call location On event without registering a new event when an old one running 

### ISSUE THREAD

**Issue by narayananl23** [transistorsoft/nativescript-background-geolocation-lt#51]
I am on the latest version of plugin and native script. Testing in android. 

Here is the situation. I am using a sidedrawer. when I start the location tracking/plugin .. it is nicely printing even the application goes to the back ground and when bought back to life.   But using side drawer, if I go to another page and come back. It is printing in my console, but the I lost the on location event. So it is not displaying on my UI. It is happening on the background. How can i get hold of the event.

Getting the state is not helping it always print the same. I can use application state to know if the tracking is on or not. but the event how can i get hold off. 

One way is.. if i call the BackgroundGeolocation.on and if an old event is running, can that be returned instead of registering a new one ? 
`BackgroundGeolocation.on("location", this.onLocation.bind(this), this.onLocationError.bind(this));
`
IOS handles the above now. The issue only happens in android.. In iOS if i call the BackgroundGeolocation.on it does not register a new event and use the old one. 

How do I know in android.. I can see that in my console printing the same as number of times I call the BackgroundGeolocation.on. In other words if i call 10 times. i see 10 time printing in the console for every location with same uuid.(only in android not in iOS)

```
viewModel.onLocation = function (location) {
        console.log(location.is_moving + "," + location.timestamp + "," + location.uuid + "," + location.coords.latitude + "," + location.coords.longitude);
        viewModel.displayDist = "";
        viewModel.dist;
        BackgroundGeolocation.getOdometer(function (distance) {
            displayDist = "Distance :" + getMeterToMiles(distance) + " Miles";
            dist = getMeterToMiles(distance);
        });
        viewModel.notifyPropertyChange("singleDistanceDisplay", displayDist);
        viewModel.notifyPropertyChange("singleDistance", dist);
    } 
```

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Nativescript version (`tns info`):
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

**Comment by narayananl23** [comment]
I also see that in IOS. It is not android only issue.

**Comment by narayananl23** [comment]
or is there a way to call bggeo.off the location ? While it is still running on background. I can call "off" before i call "on" too.

**Comment by christocracy** [comment]
You can only remove all listeners.   You cannot remove a single listener.

**Comment by narayananl23** [comment]
In my use case that is fine for now.. how ? Also can removing a single listener be added in future. In nativescript multiple view/page application that is important i think. 

When I remove, the background tracking will still run correct ?

Thanks

**Comment by christocracy** [comment]
I doubt removing single listeners will come any time soon.

**Comment by narayananl23** [comment]
I could not find from the doc.. how to turn off everything ?

**Comment by christocracy** [comment]
I implemented it for Cordova & React Native only so far.  It will come here soon.

**Comment by narayananl23** [comment]
Any update on this ?. this will save huge on multiple events.

**Comment by christocracy** [comment]
Latest updates are merged to master.
#53 

@see [`removeListeners`](https://github.com/transistorsoft/nativescript-background-geolocation-lt/blob/master/docs/README.md#removelistenerssuccessfn-failurefn)
