### ISSUE TITLE
Is_moving = false

### ISSUE THREAD

**Issue by randy-johnson** [transistorsoft/nativescript-background-geolocation-lt#56]
## Your Environment
* Plugin version: 1.4.0
* Platform: iOS or Android: Android
* OS version: 6.0.0
* Device manufacturer / model: Nexus 6P
* Nativescript version (`tns info`): 2.4
* Plugin config: Not sure what this means....

## Expected Behavior

I used this article: https://www.genymotion.com/blog/simulate-gps-movements/ to simulate driving across town.

The location event never triggers.

When I set   bgGeo.BackgroundGeolocation.watchPosition to run every few seconds the json location data is reporting a different latitude and longitude each time but the is_moving value in the returned location is set to false.  I think this is why the location event is never triggered.

Here is a sample json location:

{"location":{"activity":{"type":"still","confidence":100},"odometer":0,"battery":{"is_charging":false,"level":1},"is_moving":false,"uuid":"9ba688b9-420c-44bd-b572-33923c2af03b","coords":{"latitude":40.1427883,"longitude":-75.0026683,"accuracy":3.9,"speed":0,"heading":-1,"altitude":66.300003051758},"timestamp":"2017-02-07T12:11:37.000Z"}}

## Context

I am trying to mimic traveling from my house to a location across town which is working because I can open up Google Maps on my Genymotion emulator and watch the icon moving from my house until the location.

Here is my code so far.  It is hooked to a button click event for now while testing:

`   

    var bgGeo = require("nativescript-background-geolocation-lt");
    var appSettings = require("application-settings");
    var fetchModule = require("fetch");
    var config = require("../../shared/config"); 
    var observableModule = require("data/observable");
    var Observable = require("data/observable").Observable;

    exports.loaded = function(args) {
      
        bgGeo.BackgroundGeolocation.configure({
        license: "5647026b5a15ced50fcd3adcb2b743ab32abf2374c40d0aff875e53b15f93b60",
        desiredAccuracy: 0,
        distanceFilter: 10,
        locationUpdateInternal: 1000,
        stationaryRadius: 20,

        activityRecognitionInterval: 0,
        stopTimeout:5,

        pausesLocationUpdatesAutomatically:false,
    
        url: "http://local.dev/api/location",

        autoSync:true,
        autoSyncThreshold:0
      },function(state){
        console.log("Current State: ", state);
      }, function(error){
        console.log("Error:",error);
      });
      
      bgGeo.BackgroundGeolocation.start(function () {
                            console.log('- Start success');

      }, function(){
        console.log('Failure')
      });

    } 

    exports.buttonTapped = function(args) {
      console.log("\n\n\nButton Clicked:\n");
      bgGeo.BackgroundGeolocation.on('location', function(location) {
          var coords = location.coords;
          console.log("- Location: " + JSON.stringify(location)+"\n\n");
        });
        
        bgGeo.BackgroundGeolocation.watchPosition(function(location) {
          // console.log("- Watch position: ", JSON.stringify(location));
        }, function(errorCode) {
            alert('An location error occurred: ' + errorCode);
        }, {
            interval: 10000,    // <-- retrieve a location every 5s.
            persist: true,    // <-- default is true
        });
        

        bgGeo.BackgroundGeolocation.on('http', function(response){

          console.log("Response:", JSON.stringify(response));

        });

    }`

**Comment by christocracy** [comment]
`is_moving` is calculated by accelerometer/gyroscope-based **MotionDetection** apis.  Simulators don't have accelerometers or gyroscopes.

**Comment by christocracy** [comment]
If you want to simulate location, you have to manually execute `changePace(true)`.  You'll want to set a high `stopTimeout`.

**Comment by randy-johnson** [comment]
The function changePace(isMoving, success, failure) is provided to force the plugin to enter "moving" or "stationary" state.


Yep,  I missed that when reading the docs.  Thank You.

**Comment by christocracy** [comment]
See the wiki for "Philosophy of Operation" document.

-- 
Snet form Gmail Mobile

**Comment by randy-johnson** [comment]
I do not see that in the wiki.

**Comment by christocracy** [comment]
I forgot to copy it. See it in Cordova version:
https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Philosophy-of-Operation
