### ISSUE TITLE
get location timestamp

### ISSUE THREAD

**Issue by narayananl23** [transistorsoft/nativescript-background-geolocation-lt#58]
how to get location timestamp. It is IOS, iPhone, All latest version of TNS and BG_lt plugin.

 ```
 BackgroundGeolocation.getLocations(function(locations, taskId) {
             console.log(locations[0].description.timestamp);
             console.log(locations[0].timestamp);
             console.log(locations[0]);
              console.log(locations[0].description);
             
        try {
            for(let location of locations){
                //console.log(location.timestamp);
                //break;
            }
         } catch(e) {
            console.error("An error occurred in my application code");
        }
        BackgroundGeolocation.finish(taskId);
       });
```

All timestamp is undefined

**Comment by christocracy** [comment]
It's a bug.  [`#getLocations`](https://github.com/transistorsoft/nativescript-background-geolocation-lt/blob/master/background-geolocation.ios.ts#L198) is supposed to convert `NSArray` -> Javascript Array, just like [`getGeofences`](https://github.com/transistorsoft/nativescript-background-geolocation-lt/blob/master/background-geolocation.ios.ts#L288) does.

It'll be fixed when I push latest version soon.

**Comment by narayananl23** [comment]
Great, looking forward too

**Comment by christocracy** [comment]
Demo app running with latest plugin binaries and nativescript.  New code some soon.

```
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 2.5.1           │ 2.5.1          │ Up to date  │
│ tns-core-modules │ 2.5.1           │ 2.5.1          │ Up to date  │
│ tns-android      │ 2.5.0           │ 2.5.0          │ Up to date  │
│ tns-ios          │ 2.5.0           │ 2.5.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘
```

**Comment by christocracy** [comment]
Give the branch [`templates`](https://github.com/transistorsoft/nativescript-background-geolocation-lt/tree/templates) a try.
