### ISSUE TITLE
Nativescript-Angular IOS Service exited due to Segmentation fault: 11 on geofence event

### ISSUE THREAD

**Issue by cmstuning** [transistorsoft/nativescript-background-geolocation-lt#62]
## Your Environment
* Plugin version: "nativescript-background-geolocation-lt": "^1.5.0",
* Platform: iOS
* OS version: macOs
* Device manufacturer / model: ios simulator
* Nativescript version (`tns info`):  2.5.2
* Plugin config: 
BackgroundGeolocation.configure({
            license: 'xxxx',
            debug: false,
            desiredAccuracy: 0,
            stationaryRadius: 25,
           // distanceFilter: 50,
            activityRecognitionInterval: 10000,
            // url: 'http://localhost:8080/locations',
            autoSync: true
## Expected Behavior
BackgroundGeolocation.on('geofence', function (params, taskId) {
             console.log('geofence triggered!');
  BackgroundGeolocation.finish(taskId);
});

## Actual Behavior
13  0x1128d1884 CFRunLoopRunSpecific
14  0x115849a6f GSEventRunModal
15  0x110555c68 UIApplicationMain
16  0x10f78f97d ffi_call_unix64
17  0x12d351640
file:///app/tns_modules/nativescript-background-geolocation-lt/background-geolocation.js:441:30: JS ERROR TypeError: undefine
d is not an object (evaluating 'dictionary.allKeys')
Mar 15 10:26:20 zhens-MBP com.apple.CoreSimulator.SimDevice.C9D4290B-1E05-4600-B294-8E444D4FC96F.launchd_sim[82078] (UIKitApp
lication:com.zoeitsolutions.mobiskills[0xd46c][84193]): Service exited due to Segmentation fault: 11

## Steps to Reproduce
it happens when enters geofence

**Comment by christocracy** [comment]
Thanks, I'll check this out asap

**Comment by christocracy** [comment]
Fixed in `1.6.0`
