### ISSUE TITLE
Nativescript-Angular Android BackgroundGeolocation.on('location' does not fire in emulator

### ISSUE THREAD

**Issue by cmstuning** [transistorsoft/nativescript-background-geolocation-lt#63]
## Your Environment
Plugin version: "nativescript-background-geolocation-lt": "^1.5.0",
Platform: Android
OS version: macOs
Device manufacturer / model: Android simulator Platform 7.1.1,  Api level 25, CPU/ABI Google APIs Intel Atom (x86)
Nativescript version (tns info): 2.5.2
Plugin config:
BackgroundGeolocation.configure({
license: 'xxxx',
debug: false,
desiredAccuracy: 0,
stationaryRadius: 25,
// distanceFilter: 50,
activityRecognitionInterval: 10000,
// url: 'http://localhost:8080/locations',
autoSync: true

## Expected Behavior

Your plain Nativescript demo app works well in Android emulator and onLocation method works and fires location change. 
On real device Angular code is fired up and location is marked, but for the testing sake it's really important that it works in the standard android emulator

## Actual Behavior

  with Angular on Android emulator, on('location') method does not seems fire up. I added a console log inside the method call and it never fired.

## Steps to Reproduce

           BackgroundGeolocation.on('location', (location, taskId) => {
           console.log('location params:', JSON.stringify(location));
          // IF YOU DON'T, iOS WILL KILL YOUR APP
            BackgroundGeolocation.finish(taskId);
        }, function (errorCode) {
            console.warn("- Location error: ", errorCode);
             });

**Comment by christocracy** [comment]
The plugin triggers tracking mode with accelerometer based motion-detection API.

There is no accelerometer in emulator.

You have to manually trigger tracking with method #changePace.

**Comment by cmstuning** [comment]
It's a bit strange, cause on iOS simulator it worked ok anyway
Solved as following:
1. it seems onLocationchange in Android emulator returns is_moving:false, so it fires once and then stops forever
2. Putting  BackgroundGeolocation.changePace(true); inside BackgroundGeolocation.on('location', (location, taskId) fixes the problem and it's possible to track location in emulators with playing gpx files.
