### ISSUE TITLE
Geofence is not triggered in Android emulator with Angular

### ISSUE THREAD

**Issue by cmstuning** [transistorsoft/nativescript-background-geolocation-lt#64]
## Your Environment
Plugin version: "nativescript-background-geolocation-lt": "^1.5.0",
Platform: Android
OS version: macOs
Device manufacturer / model: Android simulator Platform 7.1.1, Api level 25, CPU/ABI Google APIs Intel Atom (x86)
Nativescript version (tns info): 2.5.2
Plugin config:
BackgroundGeolocation.configure({
license: 'xxxx',
debug: false,
desiredAccuracy: 0,
stationaryRadius: 25,
// distanceFilter: 50,
activityRecognitionInterval: 10000,
// url: 'http://localhost:8080/locations',
autoSync: true

## Expected Behavior

I expect console log on geofence trigger, but it does not happen

## Actual Behavior

console logs that 
JS: Successfully added geofence
and then it does not react on geofence crossing

## Steps to Reproduce
After I set geofence
 geofenceConf = {
    identifier: 'geofenceTest',
		 notifyOnEntry: true,
		notifyOnExit: true,
		// notifyOnDwell: model.notifyOnDwell,
		// loiteringDelay: model.loiteringDelay,
		radius: 300,
		// latitude: 37.33444843,
		// longitude: -122.04226334
        latitude: 3.8898,
		longitude: 12.5511
}

I run it after map init
BackgroundGeolocation.addGeofence(this.geofenceConf, () => console.log("Successfully added geofence"));
         BackgroundGeolocation.on('geofence',  (params, taskId) =>{
             console.log('geofence triggered!');
});

**Comment by cmstuning** [comment]
also it's related to [https://github.com/transistorsoft/nativescript-background-geolocation-lt/issues/62](url)

**Comment by christocracy** [comment]
This is not an issue with the plugin.  Google "mock fire geofence".  Nobody seems to be able to simulate firing geofences.

**Comment by cmstuning** [comment]
Yes, I confirm, that Angular-based version works on the Android device. Could you also check/test why geofence 'crashes' iOS simulator and then we'll close that issue as well.

**Comment by christocracy** [comment]
Do you have a link to this "Geofence crash in iOS simulator" issue?

**Comment by cmstuning** [comment]
it's in the issues list: https://github.com/transistorsoft/nativescript-background-geolocation-lt/issues/62
