### ISSUE TITLE
emailLog doesn't work on Android

### ISSUE THREAD

**Issue by 3rror404** [transistorsoft/nativescript-background-geolocation-lt#65]
`.emailLog()` is not implemented in the latest Android version of the plugin.

I have a number of customers who have been having issues for weeks and I desperately need this adding before I lose their business. Can you give any idea of timescale for getting this working on Android? 

Thanks

**Comment by christocracy** [comment]
You can always use `#getLog` and transmit the log to your server with an HTTP request.

**Comment by christocracy** [comment]
Is this fixed in latest?

**Comment by christocracy** [comment]
Fixed in `1.7.0` #87
