### ISSUE TITLE
Propose changes to include.gradle

### ISSUE THREAD

**Issue by randy-johnson** [transistorsoft/nativescript-background-geolocation-lt#66]
## Your Environment
* Plugin version: 1.5.0
* Platform: Android
* OS version: 7
* Device manufacturer / model: 6P GenyMotion
* Nativescript version (`tns info`): 2.5.3
* Plugin config (Not sure what this is

I have a few different plugins installed that use google play services.  

In some include.gradle files I have to open them up and change:
compile 'com.google.android.gms:play-services-location:+'
to
compile 'com.google.android.gms:play-services-location:10.2.+'

To get around this tweaks can be made to the include.gradle file:

def googlePlayServicesVersion = project.hasProperty('googlePlayServicesVersion') ? project.googlePlayServicesVersion : '+'

compile "com.google.android.gms:play-services-base:$googlePlayServicesVersion"

Would you be open to this change?  If so I can submit a pull request.

Thank You,

Randy

**Comment by christocracy** [comment]
**NO!**

**Comment by randy-johnson** [comment]
If it is a bad idea can you elaborate please?  I see other plugins use it with no problem.

**Comment by christocracy** [comment]
https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f

**Comment by christocracy** [comment]
Plugin's must not dictate to *your app* some particular version of play-services to use.  It's your app's responsibility.

One crappy plugin want 9.x.y, some other wants 10.0.2, another 10.2.1 and in a few months, there'll be 11.0.0 and a few weeks after 11.0.1.

**Comment by randy-johnson** [comment]
Thank You Sir.  Thank looks to be exactly what I need to resolve the issue.

Thank you for your follow up message too.  

I will give it a whirl tonight and see how it goes.
