### ISSUE TITLE
[Feature request] Configurable timeout for sync

### ISSUE THREAD

**Issue by 3rror404** [transistorsoft/nativescript-background-geolocation-lt#67]
I use the manual, batch sync option. In areas with poor network coverage the sync takes (I think) ~60 seconds before `onHttpError` is called. 

I need to know wether the sync has succeeded or failed before my users can start another tracking session as I need to configure some of the `extras` parameters. I would much rather this timeout could be reduced.

Could we please have the option to configure the timeout?

**Comment by christocracy** [comment]
Why must you synchronously rely on http result to "Start another tracking session"?

What if there's a local power outage that causes network to be down for 2 hours, what then?  Or your server host goes offline or any number of other things that could cause an http timeout.

You want to just keep pressing the elevator button hoping the elevator comes faster?

**Comment by 3rror404** [comment]
My statement in the initial post isn't quite accurate. I don't need to wait for the result before configuring `extras` but if the sync _is_ successful I do need to request some more information from the user before allowing them to continue. Waiting 60 seconds before knowing if the sync is going to succeed isn't ideal for me. I want to be able to reduce the timeout so I can better make a decision on how to proceed.

**Comment by christocracy** [comment]
What if the user has put their phone in their pocket before your http request finishes?

**Comment by 3rror404** [comment]
My users know how to use the app. I'm not asking you for critique. It's just a request for a feature I would find useful. I would imagine I'm not the only one who would find this useful.

**Comment by christocracy** [comment]
If it were useful to others, someone would have requested it within the last three years.

**Comment by 3rror404** [comment]
Well obviously somebody has to be the first to make a request. But anyway, forget about it. I'll find my own way.
