### ISSUE TITLE
403 status causes different behaviour between platforms

### ISSUE THREAD

**Issue by 3rror404** [transistorsoft/nativescript-background-geolocation-lt#71]
I haven't had chance to update to 1.6.0 yet so I don't know if you are aware of this or if it has already been fixed. On 1.5.0 when doing a manual sync, a 403 response triggers the `onHttp` callback on iOS and the `onHttpError` callback on Android.

**Comment by christocracy** [comment]
Yes, something about this reported and fixed for the React Native folks.  Their issue was with 401.

I might have done something for 403.

https://github.com/transistorsoft/nativescript-background-geolocation-lt/blob/master/CHANGELOG.md

**Comment by 3rror404** [comment]
Cool I'll try to update tomorrow and test. 

Also, unrelated but NativeScript 3.0 is in rc stage. I believe there are some breaking changes. https://www.nativescript.org/blog/nativescript-3.0-release-candidate-available-today

**Comment by christocracy** [comment]
Update?

**Comment by christocracy** [comment]
Should be fixed in `1.7.0` #87
