### ISSUE TITLE
heartbeat interval minimum value

### ISSUE THREAD

**Issue by randy-johnson** [transistorsoft/nativescript-background-geolocation-lt#73]
Plugin version: 1.4
Platform: Android
OS version: 7
Device manufacturer / model: Nexus 6P
Nativescript version (tns info): 2.5.3

 desiredAccuracy: 0,
        distanceFilter: 50,
        heartbeatInterval: 15,

I changed the heartbeatInterval to 15 to do some testing and it doesn't do any heartbeats less than 60 seconds even though I have it at 15.

Is 60 the minimum?

**Comment by christocracy** [comment]
60 is minimum.  Android won't even allow less than 60 with its mechanism (AlarmManager)
