### ISSUE TITLE
Module not found: Error: Can't resolve 'nativescript-background-geolocation-lt'

### ISSUE THREAD

**Issue by ChristelleThiry** [transistorsoft/nativescript-background-geolocation-lt#75]
Hi,

I try to use this plugin on my android app in debug before to buy the licence. I use nativescript and angular2 with webpack.

I have resolved compatibility of google play services with other plugins (firebase) but now when I try to use background geolocation plugin I have this issue at the compilation : 

ERROR in ./app.module.ts
Module not found: Error: Can't resolve 'nativescript-background-geolocation-lt' in '/...'
 @ ./app.module.ts 17:0-79
 @ ./app.module.ngfactory.ts
 @ ./main.aot.ts

In my I only made the import of the plugin : import { BackgroundGeolocation } from "nativescript-background-geolocation-lt";

Has anyone ever encountered this problem ?
Thanks

**Comment by christocracy** [comment]
You're trying to use the plugin in **your own app** (not booting the demo)?

If so, why are you attempting to load the plugin from "/..."?

To use the plugin in your own app, install it from npm, like any other plugin
```
tns plugin add nativescript-background-geolocation-lt
```

**Comment by ChristelleThiry** [comment]
I only use android platform for now, so I succeeded to use the plugin making the import like this : 
import { BackgroundGeolocation } from "nativescript-background-geolocation-lt/background-geolocation.android";

There is possible to have more docs on the operation of geofence even if the application isn't running ?

**Comment by christocracy** [comment]
>There is possible to have more docs on the operation of geofence even if the application isn't running ?

Your question is off-topic.  Is this issue solved?

**Comment by ChristelleThiry** [comment]
Yes this issue is solved.
