### ISSUE TITLE
Getting locations every 10 min only

### ISSUE THREAD

**Issue by EngNassar** [transistorsoft/nativescript-background-geolocation-lt#78]
Hello,
By using native script code for geolocation, my app (android) sends me the location every 10 min. How can I reduce it ? and what is the minimum period can be used?

**Comment by christocracy** [comment]
*****************************************************************
* WARNING:  If you ignore this template, your issue will be too.
*****************************************************************



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Nativescript version (`tns info`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by TareqElMasri** [comment]
Your Environment

    Plugin version:
    Platform: iOS or Android
    OS version:
    Device manufacturer / model:
    Nativescript version (tns info):
    Plugin config

Expected Behavior
Actual Behavior
Steps to Reproduce

Context
Debug logs

**Comment by TareqElMasri** [comment]
@christocracy I'm working with @EngNassar, these is the issue as you asked

# Environment
- Plugin version: 1.6.0
- Platform: Android
- OS version: 7
- Device manufacturer: Sony Xperia L1
- Nativescript version: 2.5.0
- Plugin config:
```
          BackgroundGeolocation.configure({
            debug: false,
            desiredAccuracy: 0,
            stationaryRadius: 25,
            distanceFilter: 50,
            activityRecognitionInterval: 10,
            url: '...',
            autoSync: true
          }, function(state) {
              BackgroundGeolocation.start();
          }.bind(this));
```
# Expected Behavior
It should send the location every 50 meters to defined http url
# Actual Behavior
It sends every 10 min

**Comment by christocracy** [comment]
Logs please.  See [`getLog`](https://github.com/transistorsoft/nativescript-background-geolocation-lt/tree/master/docs#getlogcallbackfn) or [`emailLog`](https://github.com/transistorsoft/nativescript-background-geolocation-lt/tree/master/docs#emaillogemail-callbackfn) methods.

**Comment by TareqElMasri** [comment]
JS: ║ BackgroundGeolocation adapter
JS: ╠═════════════════════════════════════════════
JS:
JS: 06-06 18:21:15.669 DEBUG [SQLiteLocationDAO dbh]
JS:   ✅  Opened database
JS: 06-06 18:21:15.708 DEBUG [SQLiteLocationDAO prune]
JS:   ℹ️  PRUNE -1 days
JS: 06-06 18:21:15.761 DEBUG [GeofenceDAO dbh]
JS:   ✅  Opened database
JS: 06-06 18:21:15.791 INFO [BackgroundGeolocation <init>]
JS:   🔵  Connecting to GooglePlayServices...
JS: 06-06 18:21:15.883 INFO [Settings print]
JS: ╔═════════════════════════════════════════════
JS: ║ BackgroundGeolocation Settings
JS: ╠═════════════════════════════════════════════
JS: {
JS:   "isMoving": false,
JS:   "enabled": false,
JS:   "odometer": 0,
JS:   "schedulerEnabled": false,
JS:   "trackingMode": "location",
JS:   "distanceFilter": 50,
JS:   "desiredAccuracy": 0,
JS:   "desiredOdometerAccuracy": 100,
JS:   "locationUpdateInterval": 1000,
JS:   "fastestLocationUpdateInterval": 10000,
JS:   "locationTimeout": 60,
JS:   "deferTime": 0,
JS:   "disableElasticity": false,
JS:   "activityRecognitionInterval": 10,
JS:   "minimumActivityRecognitionConfidence": 75,
JS:   "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
JS:   "disableStopDetection": false,
JS:   "stationaryRadius": 25,
JS:   "stopTimeout": 0,
JS:   "url": "http:\/\/imaxem.com\/maxorderb\/en\/userTrack",
JS:   "method": "POST",
JS:   "autoSync": true,
JS:   "autoSyncThreshold": 0,
JS:   "batchSync": false,
JS:   "maxBatchSize": -1,
JS:   "params": {
JS:     "userId": "13",
JS:     "orderId": null
JS:   },
JS:   "headers": {},
JS:   "extras": {},
JS:   "httpRootProperty": "location",
JS:   "locationTemplate": "",
JS:   "geofenceTemplate": "",
JS:   "persist": true,
JS:   "maxDaysToPersist": 1,
JS:   "maxRecordsToPersist": -1,
JS:   "locationsOrderDirection": "ASC",
JS:   "geofenceProximityRadius": 1000,
JS:   "geofenceInitialTriggerEntry": true,
JS:   "stopOnTerminate": true,
JS:   "startOnBoot": false,
JS:   "heartbeatInterval": -1,
JS:   "foregroundService": false,
JS:   "notificationTitle": "",
JS:   "notificationText": "Location Service activated",
JS:   "notificationColor": "",
JS:   "notificationIcon": "",
JS:   "forceReloadOnLocationChange": false,
JS:   "forceReloadOnMotionChange": false,
JS:   "forceReloadOnGeofence": false,
JS:   "forceReloadOnBoot": false,
JS:   "forceReloadOnHeartbeat": false,
JS:   "forceReloadOnSchedule": false,
JS:   "stopAfterElapsedMinutes": 0,
JS:   "schedule": [],
JS:   "configureUrl": "",
JS:   "configureInterval": -1,
JS:   "debug": false,
JS:   "logLevel": 5,
JS:   "logMaxDays": 3
JS: }╚══════════════════════════════
JS: olocation requestActivityUpdates]
JS:   🎾  Start activity updates: 10
JS: 06-06 18:21:17.660 INFO [BackgroundGeolocationService a]
JS:   🔵  setPace: null → false
JS: 06-06 18:21:18.249 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
JS: 06-06 18:21:18.266 DEBUG [BackgroundGeolocation isMainActivityActive] YES
JS: 06-06 18:21:34.476 INFO [BackgroundGeolocation$m onReceive]
JS: ╔═════════════════════════════════════════════
JS: ║ Location-provider change: true
JS: ╠═════════════════════════════════════════════
JS: ╟─ GPS: true
JS: ╟─ Network: true
JS:
JS: 06-06 18:21:47.579 DEBUG [LocationService onLocation]
JS: ╔═════════════════════════════════════════════
JS: ║ LocationService: location:1001
JS: ╠═════════════════════════════════════════════
JS: ╟─ 📍  Location[fused 30.132561,31.363441 acc=104 et=+7d5h41m29s631ms]
JS:
JS: 06-06 18:21:47.827 DEBUG [TSLocationManager calculateMedianAccuracy] 104.1
JS: 06-06 18:21:48.120 DEBUG [LocationService onLocation]
JS: ╔═════════════════════════════════════════════
JS: ║ LocationService: location:1001
JS: ╠═════════════════════════════════════════════
JS: ╟─ 📍  Location[fused 30.132564,31.363440 acc=942 et=+7d5h41m30s700ms alt=0.0]
JS:
JS: 06-06 18:21:48.351 DEBUG [TSLocationManager calculateMedianAccuracy] 523.05
JS: 06-06 18:21:48.780 DEBUG [LocationService onLocation]
JS: ╔═════════════════════════════════════════════
JS: ║ LocationService: location:1001
JS: ╠═════════════════════════════════════════════
JS: ╟─ 📍  Location[fused 30.132564,31.363440 acc=968 et=+7d5h41m31s699ms alt=0.0]
JS:
JS: 06-06 18:21:48.882 INFO [TSLocationManager onSingleLocationResult]
JS:   🔵  Acquired providerchange position
JS: 06-06 18:21:48.947 DEBUG [TSLocationManager calculateMedianAccuracy] 104.1
JS: 06-06 18:21:49.084 INFO [SQLiteLocationDAO persist]
JS:   ✅  INSERT: dfe9fe94-1605-4c05-b2f9-d214acc5878f
JS: 06-06 18:21:49.096 DEBUG [BackgroundGeolocationService onActivityRecognitionResult] still (100%)
JS: 06-06 18:21:49.246 DEBUG [BackgroundGeolocation isMainActivityActive] YES
JS: 06-06 18:21:49.263 DEBUG [HttpService flush]
JS: ╔═════════════════════════════════════════════
JS: ║ HTTP Service
JS: ╠═════════════════════════════════════════════
JS:
JS: 06-06 18:21:49.359 DEBUG [SQLiteLocationDAO first]
JS:   ✅  Locked 1 records
JS: 06-06 18:21:49.413 INFO [HttpService createRequest]
JS:   🔵  POST: 61c9fa1b-3fe7-4fce-9699-77a303cc1ac4
JS: 06-06 18:21:50.625 INFO [HttpRequest parseNetworkResponse]
JS:   🔵  Response: 200
JS: 06-06 18:21:50.681 DEBUG [SQLiteLocationDAO destroy]
JS:   ✅  DESTROY: 61c9fa1b-3fe7-4fce-9699-77a303cc1ac4
JS: 06-06 18:21:50.777 DEBUG [SQLiteLocationDAO first]
JS:   ✅  Locked 1 records
JS: 06-06 18:21:50.800 INFO [HttpService createRequest]
JS:   🔵  POST: 61c9fa1b-3fe7-4fce-9699-77a303cc1ac4
JS: 06-06 18:21:50.852 INFO [HttpRequest parseNetworkResponse]
JS:   🔵  Response: 200
JS: 06-06 18:21:50.882 DEBUG [SQLiteLocationDAO destroy]
JS:   ✅  DESTROY: 61c9fa1b-3fe7-4fce-9699-77a303cc1ac4
JS: 06-06 18:21:50.979 DEBUG [SQLiteLocationDAO first]
JS:   ✅  Locked 1 records
JS: 06-06 18:31:07.570 INFO [HttpService createRequest]
JS:   🔵  POST: dfe9fe94-1605-4c05-b2f9-d214acc5878f
JS: 06-06 18:21:51.084 INFO [HttpRequest parseNetworkResponse]
JS:   🔵  Response: 200
JS: 06-06 18:21:
JS: ainActivityActive] YES
JS: 06-06 18:31:07.454 INFO [BackgroundGeolocation onActivityDestroy]
JS: ╔═════════════════════════════════════════════
JS: ║ MainActivity was destroyed
JS: ╠═════════════════════════════════════════════
JS: ╟─ stopOnTerminate: true
JS: ╟─ enabled: true
JS:
JS: 06-06 18:31:07.473 INFO [TSLocationManager stopWatchPosition]
JS:   🔴  watchPosition: OFF
JS: 06-06 18:31:07.493 DEBUG [BackgroundGeolocation f]
JS:   🔴  Cleared callbacks
JS: 06-06 18:31:07.521 INFO [BackgroundGeolocation removeActivityUpdates]
JS:   🔴  Stop activity updates
JS: 06-06 18:31:07.548 INFO [SQLiteLocationDAO close]
JS:   ✅  Closed database
JS: 06-06 18:31:07.570 INFO [TSLocationManager stopWatchPosition]
JS:   🔴  watchPosition: OFF
JS: 06-06 18:31:11.139 DEBUG [BackgroundGeolocationService onDestroy]
JS: ╔═════════════════════════════════════════════
JS: ║ BackgroundGeolocationService destroyed
JS: ╠═════════════════════════════════════════════
JS:
JS: 06-06 18:31:11.163 INFO [BackgroundGeolocationService i]
JS:   🔴  Stop heartbeat
JS: 06-06 18:32:01.936 INFO [BackgroundGeolocation <init>]
JS: ╔═════════════════════════════════════════════
JS: ║ BackgroundGeolocation adapter
JS: ╠═════════════════════════════════════════════
JS:
JS: 06-06 18:32:01.994 DEBUG [SQLiteLocationDAO dbh]
JS:   ✅  Opened database
JS: 06-06 18:32:02.027 DEBUG [SQLiteLocationDAO prune]
JS:   ℹ️  PRUNE -1 days
JS: 06-06 18:32:02.090 DEBUG [GeofenceDAO dbh]
JS:   ✅  Opened database
JS: 06-06 18:32:02.116 INFO [BackgroundGeolocation <init>]
JS:   🔵  Connecting to GooglePlayServices...

**Comment by christocracy** [comment]
You don't need to split the log on `\n` if you're simply going to print it.

```
bgGeo.getLog(function(log) {
  console.log(log);  // <------- just throw it on console.
});
```

**Comment by christocracy** [comment]
If you want the plugin to stay alive after terminating, you must tell it to:  `stopOnTerminate: false`.

```
JS: ╔═════════════════════════════════════════════
JS: ║ MainActivity was destroyed
JS: ╠═════════════════════════════════════════════
JS: ╟─ stopOnTerminate: true
JS: ╟─ enabled: true
```

**Comment by TareqElMasri** [comment]
That didn't solve the issue

**Comment by TareqElMasri** [comment]
@christocracy emaillog method isn't working in android, will that be fixed soon?

**Comment by christocracy** [comment]
I'll look into it Monday.

**Comment by EngNassar** [comment]
Hello @christocracy 

Hope all is well.

We are waiting your kind reply. Your quick assistance is highly appreciated, as we spent a lot of time trying to solve this issue with no success, although it is working properly in iOS.

Thank you for your understanding.

**Comment by christocracy** [comment]
I'm working with NativeScript all day today, trying to get my demo to boot with latest NS 3.0.1.

What version of NS are you using?

**Comment by TareqElMasri** [comment]
2.5.0

**Comment by christocracy** [comment]
Try installing from branch [latest-updates](https://github.com/transistorsoft/nativescript-background-geolocation-lt/tree/latest-updates)

See [README](https://github.com/transistorsoft/nativescript-background-geolocation-lt#from-master-latest-greatest) for instructions on how to plugin from git.

```
$ git clone https://github.com/transistorsoft/nativescript-background-geolocation-lt.git
$ cd nativescript-background-geolocation-lt
$ git checkout origin/latest-updates
$ npm install
$ tsc
```
The plugin is compiled and ready to be added to your app:
```
$ tns plugin add /path/to/nativescript-background-geolocation-lt
```

**Comment by EngNassar** [comment]
Unfortunately the issue is still existing

**Comment by christocracy** [comment]
I'm not convinced there's anything "wrong" the plugin.  That release implement emailLog for Android to assist with providing logs.

**Comment by EngNassar** [comment]
ok I see.....will try it again to review the log and send you our feedback.

Thank you

**Comment by TareqElMasri** [comment]
I've tried using heartbeat with changePace, it works fine with the local server, although with a live server it still timeout with every 10 minutes, I've attached a log from the application so hopefully you can tell me what's wrong with it.
https://gist.github.com/TareqElMasri/fe3ebee23debca707fdb9512b6aeeb7d

And that's the configurations I'm using right now
```
          BackgroundGeolocation.configure({
            debug: false,
            desiredAccuracy: 0,
            stationaryRadius: 25,
            distanceFilter: 50,
            stopOnTerminate: false,
            heartbeatInterval: 5,
            activityRecognitionInterval: 10,
            autoSync: true
          }, function (state) {
            BackgroundGeolocation.start();
            BackgroundGeolocation.on('heartbeat', (location, taskId) => {
              BackgroundGeolocation.changePace(true);
            });
          }.bind(this));
          BackgroundGeolocation.getLog(function (log) {
            console.log(log);
          });
```

**Comment by christocracy** [comment]
@TareqElMasri This issue is titled "*Getting locations every 10 min only #78
*".  Is that what you're trying to do?

**Comment by TareqElMasri** [comment]
No, I'm trying to get a location for every 10 seconds, getting it every 10 minutes is the issue we're having

**Comment by christocracy** [comment]
@TareqElMasri is the device *moving* when you're expecting a location every 10 s?

**Comment by christocracy** [comment]
I don't see anything unusual in your logs.  I suggest you set `debug: true` and go out for a field-test and *listen* to the debug sounds.

**Comment by TareqElMasri** [comment]
We did a field-test many times with the same result, and what's strange about it that it works good with iOS, only on Android the error occurs

**Comment by christocracy** [comment]
It's not strange at all that behaviour between iOS and Android could be different.  There are far more types of Android device out there and some are crappy.

What device make / model are you having issues with?

**Comment by EngNassar** [comment]
Hello Chris,

Good day.

Kindly be informed that we have purchased the plugin since 2 months ago, and since that time we are trying to debug this issue for Android Platform (it works fine in iOS) to make sure to fix any issue or bug from our side if any, so we are sure that we don't have any issue in our side or server, as well as the plugin is working properly in iOS.

So, your help and interest is highly appreciated to help us fix and finalize this issue permanently.

BTW, we used many Android devices and versions as following:
1- Sony Xperia L1, Android V.7
2- ViewSonic Tablet, Android V.5

**Comment by christocracy** [comment]
Is your tablet Wifi only?  Performance of Wifi-only tablets is going to be poor since they typically missing many sensors, including GPS.

Do you have a map screenshot of this behaviour?

**Comment by EngNassar** [comment]
The mobile (Sony Xperia) is 4G mobile, and the tablet is Wifi only....So I have tried both but I got same result

**Comment by EngNassar** [comment]
our issue can't be shown in a screenshot....we are sending the location to a database. then it is shown in our map in our web application....We are trying to develop an app which can let other user tracks him through a web application.
So, the location in the web application is changed every 10 min, although our configurations were set to change the location every 10 sec.

**Comment by christocracy** [comment]
Go test with `debug: true`.  

- When you *hear* the plugin say *doodly-doo*, the plugin began aggressively tracking and will record a location each `distanceFilter` meters.
- When you *hear* the plugin say *blip*, a location was recorded.
- When you *hear* the plugin say *beeeeeeeep* (long beep), the plugin entered **stationary** mode and stopped tracking.

**Comment by EngNassar** [comment]
what if the plugin entered "stationary" mode? what should we do ?

**Comment by christocracy** [comment]
>what if the plugin entered "stationary" mode? what should we do ?

That's  completely normal thing for the plugin to do -- this is the plugin's preferred state to be in.  What  should you do?  *move*.

Read the [Philosophy of Operation](https://github.com/transistorsoft/nativescript-background-geolocation-lt/wiki/Philosophy-of-Operation)

**Comment by EngNassar** [comment]
yes I know that....but my question about what if it happened when we move !!?

**Comment by christocracy** [comment]
Location-services has nothing to do with what network your device is *actually* connected to.

Go do a field-test and listen for *blip*...*blip*...*blip* as you're moving.

**Comment by christocracy** [comment]
>but my question about what if it happened when we move !!?

It's very simple:  "When you hear the plugin say beeeeeeeep (long beep), the plugin entered stationary mode and stopped tracking."

Have you observed the plugin entering **stationary** mode while the device is moving?

**Comment by EngNassar** [comment]
ok...we have created a new apk
will test it now and will send you our feedback very very soon

**Comment by EngNassar** [comment]
hello Chris,,,

I have tested the plugin by myself, and I confirm that all beeps are working properly with me, and when moving I get beep every 10 seconds exactly...

But my map doesn't change the location except after 10 min from each gotten location.

So, what do you think?

**Comment by christocracy** [comment]
I would check your http code.  You're not using the plugin's http Service, so you're obviously relying on your JavaScript running, which is a bad idea, since the OS can terminate the foreground activity (where your JavaScript app lives) when under memory pressure.

I have no idea if that's the case, but the issue is clearly in your own code.  When you hear *blip*, the plugin has recorded and inserted a location into its database.

**Comment by TareqElMasri** [comment]
I'm using the plugin's http service through the "url" parameter

**Comment by christocracy** [comment]
Send logs of latest test.

**Comment by TareqElMasri** [comment]
https://gist.github.com/TareqElMasri/d5ff75e0f52a65b2ef231a146988e687

**Comment by christocracy** [comment]
That's only 30s of logs.  I need a whole field-test of like 2km or so.

**Comment by TareqElMasri** [comment]
Latest log
https://gist.github.com/TareqElMasri/56fbbd95b2d2c73f894da0b6f12bc864

**Comment by christocracy** [comment]
Search your log for "Response".  These log-entries are the response from *your* server.  There were 116 locations successfully sent to your server.

eg:

 🔵  POST: 9892cffe-6831-4e8b-8c93-623f72368dd6
07-29 21:36:05.127 INFO [HttpRequest parseNetworkResponse] 
  🔵  Response: 200
