### ISSUE TITLE
my app is crashing on initialization of plugin in IOS

### ISSUE THREAD

**Issue by randy-johnson** [transistorsoft/nativescript-background-geolocation-lt#79]
## Your Environment
* Plugin version: Compiled a couple days ago from naster
* Platform: iOS or Android IOS
* OS version: 10.12.5
* Device manufacturer / model:  IOS Emulator
* Nativescript version (`tns info`): 3.0.3
* Plugin config

{
        license: "",
        desiredAccuracy: 0,
        distanceFilter: 50,
        heartbeatInterval: 60*15,
        foregroundService: false,
        url: config.apiUrl+"api",
        method:"POST",
        autoSync: true,
        startOnBoot:true

    }

## Expected Behavior

the plugin initializes and works

## Actual Behavior

I get the following error in IOS in the console and then the app crashes.  It works fine in android, but ios is giving issues

```
🔵-[Settings init] Settings loaded
🔵-[Settings setOdometer:] 0
*** Assertion failure in -[CLLocationManager setAllowsBackgroundLocationUpdates:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreLocationFramework_Sim/CoreLocation-2101.0.62/Framework/CoreLocation/CLLoc
ationManager.m:649
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: !stayUp || CLClientIsBackgroundable(internal->fClient)'
        *** First throw call stack:
        (
                0   CoreFoundation                      0x000000010fbd5b0b __exceptionPreprocess + 171
                1   libobjc.A.dylib                     0x000000010f132141 objc_exception_throw + 48
                2   CoreFoundation                      0x000000010fbd9cf2 +[NSException raise:format:arguments:] + 98
                3   Foundation                          0x000000010e8e4536 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
                4   CoreLocation                        0x000000010afad95b CLClientGetCapabilities + 10739
                5   locallyepicapp                      0x0000000108b7eeb6 -[TSGeofenceManager init] + 147
                6   locallyepicapp                      0x0000000108b84c52 -[TSLocationManager init] + 1181
                7   locallyepicapp                      0x0000000108b8478f __35+[TSLocationManager sharedInstance]_block_invoke + 38
                8   libdispatch.dylib                   0x0000000110441792 _dispatch_client_callout + 8
                9   libdispatch.dylib                   0x000000011042ca8d dispatch_once_f + 69
                10  locallyepicapp                      0x0000000108b84767 +[TSLocationManager sharedInstance] + 102
                11  NativeScript                        0x000000010e58f8ed ffi_call_unix64 + 85
                12  ???                                 0x0000000127f27a90 0x0 + 4965169808
        )Jun 24 14:55:28
```

## Steps to Reproduce

1.
2.
3.
4.

## Context

the app starts up and then when it goes to initialize the plugin I get the above error.

I added the following code to my app.js file:

```
var nativescript_background_fetch_1 = require("nativescript-background-fetch");
var MyDelegate = (function (_super) {
        __extends(MyDelegate, _super);
        function MyDelegate() {
            return _super !== null && _super.apply(this, arguments) || this;
        }
        MyDelegate.prototype.applicationPerformFetchWithCompletionHandler = function (application, completionHandler) {
            var controller = application.keyWindow.rootViewController;
            console.log('********** controller: ', controller);
            console.log('- AppDelegate Rx Fetch event');
            nativescript_background_fetch_1.BackgroundFetch.performFetchWithCompletionHandler(completionHandler);
        };
        return MyDelegate;
    }(UIResponder));
    MyDelegate.ObjCProtocols = [UIApplicationDelegate];
    application.ios.delegate = MyDelegate;


```

I have been through the documentation a couple different times and do not see anything I missed, but I must have missed something.  Any ideas?

**Comment by christocracy** [comment]
Somehow background location capability has been disabled in your Xcode project.  Ensure background location capability is enabled

**Comment by randy-johnson** [comment]
I opened up the info.plist file added a row in Required background modes with value "App registers for location updates"  and that removed the error.  I am still getting a crash though.  This is what I see in console now:

-[Settings init] Settings loaded
🔵-[Settings setOdometer:] 0

Jun 24 15:35:33 Randys-iMac com.apple.CoreSimulator.SimDevice.AB98DCE4-B911-4B69-8F11-FF7510820DF9.launchd_sim[3036] (UIKitApplication:com.myyapp[0x1be7][3058
][8544]): Service exited due to Segmentation fault: 11

If I comment out the plugin code the crash stops.  Here is the device log:
```
	=======================================RUNNING CONFIG RUNNING CONFIG
Jun 24 15:38:06 Randys-iMac locallyepicapp[8589]: 🔵-[Settings init] Settings loaded
Jun 24 15:38:06 Randys-iMac locallyepicapp[8589]: 🔵-[Settings setOdometer:] 0
Jun 24 15:38:06 Randys-iMac SpringBoard[3053]: UNSUserNotificationServerConnectionListener connection invalidated
Jun 24 15:38:06 Randys-iMac SpringBoard[3053]: [KeyboardArbiter] HW kbd: Failed to set (null) as keyboard focus
Jun 24 15:38:06 Randys-iMac com.apple.CoreSimulator.SimDevice.AB98DCE4-B911-4B69-8F11-FF7510820DF9.launchd_sim[3036] (UIKitApplication:com.myapp[0xdc03][3058][8589]): Service exited due to Segmentation fault: 11
Jun 24 15:38:07 Randys-iMac assertiond[3058]: Deleted job with label: UIKitApplication:com.myapp[0xdc03][3058]
Jun 24 15:41:45 Randys-iMac CoreSimulatorBridge[3059]: Pasteboard change listener callback port <NSMachPort: 0x7f999390b700> registered
```

**Comment by christocracy** [comment]
There's no reference to TSLocationManager.  Your issue is with some other component

**Comment by randy-johnson** [comment]
ok,  I will close this ticket for now.  Thank You for your help.

**Comment by randy-johnson** [comment]
Hello Chris,

I found out what was causing the latest crash.

In the params part of my plugin config where  I am sending variables back t, one of the variables I was using was null.

Is there a reason why it wouldn't handle null values being passed?

**Comment by christocracy** [comment]
Yes, iOS doesn't like null in #params when converting a JSONObject to native NSDictionary.

In the meantime, ensure you don't send null values in #params

**Comment by randy-johnson** [comment]
ok, thank you,   yes that does indeed resolve the issue.
