### ISSUE TITLE
setOdometer(0) / resetOdometer

### ISSUE THREAD

**Issue by 3rror404** [transistorsoft/nativescript-background-geolocation-lt#81]
Hi Chris,

there was a discussion a while back on the Cordova repository about how `setOdometer(0)` / `resetOdometer` work. I can't access the Cordova repo any more as my licence has expired (I will be renewing) so I can't see your response or link to the thread.

I think you agreed with an analogy I made about transporting a car (the device) in the back of a truck between `stop` and `start` events and that the plugin should have no knowledge of the distance traveled during this time.

Did this change ever make it into the Cordova version and will it make it over to NS?

Thanks

Edit: I have found your response in an email notification but I cant remember the exact situation I was describing at the time.

> Ok @3rror404, your "back of truck" analogy makes sense. I will simply nullify the odometer reference coordinate on #stop.
 [Here is the thread](https://github.com/transistorsoft/cordova-background-geolocation/issues/839#issuecomment-297761850)

**Comment by christocracy** [comment]
Yes, that has been pushed here.

**Comment by christocracy** [comment]
Sorry, hasn't been merged to master yet.

It's in [lastest-updates](https://github.com/transistorsoft/nativescript-background-geolocation-lt/commits/latest-updates) branch.

**Comment by 3rror404** [comment]
Hi Chris, I've just got around to testing the "latest-updates" branch. Is `getState()` working for you? 

On iOS I get no output:

```
BackgroundGeolocation.getState(function(state) {
    console.log(JSON.stringify(state));
});
```

```
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 3.2.1           │ 3.2.1          │ Up to date    │
│ tns-core-modules │ 3.2.0           │ 3.2.0          │ Up to date    │
│ tns-android      │                 │ 3.2.0          │ Not installed │
│ tns-ios          │ 3.2.0           │ 3.2.0          │ Up to date    │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
```

**Comment by 3rror404** [comment]
Forget that, I was actually using the `master` branch. `latest-updates` looks to work fine but the `master` branch seems to have issue with N3.2.x

**Comment by christocracy** [comment]
Big update released.  @see #87
