### ISSUE TITLE
iOS 11 Compatability

### ISSUE THREAD

**Issue by ShawnPavel** [transistorsoft/nativescript-background-geolocation-lt#83]
## Your Environment
* Plugin version:
* Platform: iOS
* OS version: 11
* Device manufacturer / model: all models
* Nativescript version (`tns info`): 3.x

## Expected Behavior
While calling the configure method permissions are asked.
After confirming permissions the module starts working.

## Actual Behavior
Nothing happens. No permissions for geolocation and probably therefore also no working module.

## Steps to Reproduce
1. Install latest Xcode
2. Run on a device with iOS11

## Context
It appears this issue has already been logged on the [React Native version](https://github.com/transistorsoft/react-native-background-geolocation/issues/282)

**Comment by christocracy** [comment]
Big update coming soon.

**Comment by christocracy** [comment]
Fixed in #87
