### ISSUE TITLE
Webpack Plugin Resolution

### ISSUE THREAD

**Issue by ShawnPavel** [transistorsoft/nativescript-background-geolocation-lt#84]
When attempting to webpack my application after adding the background-geolocation/background-fetch plugins it fails when trying to resolve the plugins. Is webpack supported by the backgorund-geolocation plugin? If so, what steps can I take to attempt to remedy the module resolution?

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version: ^1.6.0
* Nativescript version (`tns info`): 2.5.5
* Plugin config

```
{
    license: '***',
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_LOW, // Default: HIGH
    distanceFilter: 10,
    stationaryRadius: 25, // 25 RAISE TO 100 when done testing
    useSignificantChangesOnly: true, // false
    activityRecognitionInterval: 120 * 1000, // 10000
    stopTimeout: 1,
    disableMotionActivityUpdates: true,
    maxRecordsToPersist: 1,
    stopOnTerminate: false,
    startOnBoot: true,
    heartbeatInterval: 300,
    debug: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_INFO,
    logMaxDays: 3
}
```

## Expected Behavior
When running webpack the plugin(s) should resolve

## Actual Behavior
Webpack fails to resolve the plugins

## Webpack Error
```
ERROR in ./core/services/background-location.service.ts
Module not found: Error: Can't resolve 'nativescript-background-geolocation-lt' in '/Users/shawnpavel/Development/mobileClassic/app/core/services'
 @ ./core/services/background-location.service.ts 3:47-96
 @ ./app.module.ngfactory.ts
 @ ./main.aot.ts

ERROR in ./shared/utils/background-geolocation.util.ts
Module not found: Error: Can't resolve 'nativescript-background-geolocation-lt' in '/Users/shawnpavel/Development/mobileClassic/app/shared/utils'
 @ ./shared/utils/background-geolocation.util.ts 3:47-96
 @ ./shared/utils/index.ts
 @ ./shared/providers/firebase-remote-config.ts
 @ ./app.module.ngfactory.ts
 @ ./main.aot.ts

ERROR in ./shared/utils/app-event-setup.util.ts
Module not found: Error: Can't resolve 'nativescript-background-fetch' in '/Users/shawnpavel/Development/mobileClassic/app/shared/utils'
 @ ./shared/utils/app-event-setup.util.ts 3:38-78
 @ ./shared/utils/index.ts
 @ ./shared/providers/firebase-remote-config.ts
 @ ./app.module.ngfactory.ts
 @ ./main.aot.ts
```

**Comment by christocracy** [comment]
The plugin is not involved with Webpack.  This is NativeScript responsibility.

**Comment by shaunlmason** [comment]
The issue appears to be that module resolution depends on the package export either being `index.js` OR remove the `.js` extension in the package.json file.  I'm not sure what the issue in resolution is, but there is definitely a difference in the way the two cases are resolved.

**Comment by bradmartin** [comment]
It's how webpack works actually. So it's fine to remove the extension.

**Comment by shaunlmason** [comment]
@bradmartin Out of curiosity, does that difference in resolution happen outside the NativeScript ecosystem?

**Comment by bradmartin** [comment]
It works fine outside of NS.

**Comment by bradmartin** [comment]
https://github.com/bradmartin/mystical-notification/blob/master/package.json#L5 Here is an example of a browser thing I wrote which uses webpack to build, notice the package json `main` key 👍

**Comment by bradmartin** [comment]
I suppose the plugin doesn't have to drop the `.js` extension but it doesn't matter to the plugin to have the extension, it just lets the plugin support webpack and all NS apps 👍 so whatever. I don't use it so doesn't affect me really.

**Comment by shaunlmason** [comment]
So the `resolve.extensions` field in webpack.config dictates file type I suppose?

**Comment by ShawnPavel** [comment]
I can confirm that removing the `.js` from the main value resolved the issue.

**Comment by bradmartin** [comment]
That I do not know about. I'm no webpack expert, I just know you don't have to specify the extension in the package.json for webpack to resolve a module. Outside of that, I don't know much about it.

**Comment by shaunlmason** [comment]
Gotcha, appreciate the discussion @bradmartin.  It's nice to run across people who are actually helpful.=)

**Comment by christocracy** [comment]
@ShawnPavel do you want me to change in my `package.json`?  I'm due to push a big update soon.

**Comment by ShawnPavel** [comment]
@christocracy If you were to change it to not require the `.js` it would allow anyone who uses the plugin to webpack. So I would say. I would appreciate it very much. This same issue is present in the background-fetch plugin as well.

**Comment by christocracy** [comment]
So `"main": "background-geolocation" ?

**Comment by ShawnPavel** [comment]
Yes, sir.

**Comment by christocracy** [comment]
`nativescript-background-geolocation-lt @ 1.7.0` and `nativescript-background-fetch @ 1.0.1` are now published.  `.js` removed from `package.json` in both plugins.
