### ISSUE TITLE
Android Oreo Persistent Notification

### ISSUE THREAD

**Issue by ShawnPavel** [transistorsoft/nativescript-background-geolocation-lt#90]
## Your Environment
* Plugin version: 1.7.0
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Google Pixel 2
* Nativescript version (`tns info`):
```
nativescript: 3.2.1
tns-core-modules: 3.2.0 
tns-android: 3.2.0 
```
* Plugin config
```typescript
    let options = {
        license: 'xxx',

        /* *****
            [Geolocation] Common Options
         * *****/
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_LOW,
        distanceFilter: 150,

        /* *****
            [Geolocation] iOS Options
         * *****/
        stationaryRadius: 100,
        useSignificantChangesOnly: true,

        /* *****
            [Activity Recognition] iOS Options
         * *****/
        disableMotionActivityUpdates: true,

        /* *****
            HTTP & Persistence Options
         * *****/
        url: LsApiPathConfig.API_URL + LsApiPathConfig.USER_LOCATION,
        extras: this.getBackgroundGeolocationExtras(),
        httpRootProperty: '.',
        maxRecordsToPersist: 1,

        /* *****
            [Application] Common Options
         * *****/
        stopOnTerminate: false,
        startOnBoot: true,
        heartbeatInterval: 300,

        /* *****
            [Application] Android Options
         * *****/
        foregroundService: false,
        notificationTitle: 'LiveShopper',
        notificationText: 'Location service activated',
        notificationIcon: 'drawable/ls_notification',

        /* *****
            Logging and Debug Options
         * *****/
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        logMaxDays: 3
    };
```

## Expected Behavior
When configured with `foregroundService: false` there should not be a notification present.

## Actual Behavior
There is always a notification present despite the `foregroundService` configured value.

## Steps to Reproduce
1. Configure foreground service to false
2. Launch on Android Oreo OS

**Comment by christocracy** [comment]
This is correct.  Due to strict new [Background Execution Limits](https://developer.android.com/about/versions/oreo/background.html) in Android 8, `foregroundService: true` is now required when building for Android 8.

From the [Background Execution Limits](https://developer.android.com/about/versions/oreo/background.html)

>Prior to Android 8.0, the usual way to create a foreground service was to create a background service, then promote that service to the foreground. **With Android 8.0, there is a complication;** the system **doesn't allow a background app to create a background service**. For this reason, Android 8.0 introduces the new method startForegroundService() to start a new service in the foreground. **After the system has created the service, the app has five seconds to call the service's startForeground() method to show the new service's user-visible notification. If the app does not call startForeground() within the time limit, the system stops the service and declares the app to be ANR (Application Not Responding)**.

**Comment by ShawnPavel** [comment]
So the icon will always show no matter what? If I were to configure the plugin to give me points once every 5 minutes, would the notification only show while accessing/processing the location?

**Comment by christocracy** [comment]
- If you call `#start`, the plugin's foreground-service is running (including associated icon)
- If you call `#stop`, the plugin's foreground-service is terminated.

**Comment by ShawnPavel** [comment]
So does that mean the notification will always be shown if I am using the plugin?

**Comment by christocracy** [comment]
>So does that mean the notification will always be shown if I am using the plugin?

```javascript
BackgroundGeolocation.start(() => {
  // Notification icon is now showing.
  BackgroundGeolocation.stop(() => {
    // Notification icon is now off.
  }); 
});
```

**Comment by ShawnPavel** [comment]
Ok. I see that you can start and stop the service. Thanks.

If I stop the service, the notification goes away. BUT it also will also stop sending locations to my server. What I want to know, is if there is a way for me to periodically get a location update in the background, without having the notification ALWAYS show up, even when it's not actively getting a location. 

For example, I use an application called Life360 on my phone. It shares my location with my family and vice versa even when the application is closed. I barely ever see a notification for that app show up in my notification bar. When it does, it's only there for a second. Yet, my location is still actively shared with my family.

**Comment by christocracy** [comment]
This plugin is designed for aggressive tracking of device location.  It's primarily designed for "fleet-tracking" applications (eg: disaster-response, taxi, exercise apps).  It's not designed for "social" apps, like Life 360.

Life360 may be using server push notifications to periodically send silent "where are you?" notifications (ie: a push notification with only a JSON payload) from the server (which is a good idea).  You can certainly have your server send silent push notifications to your app, where you could execute `BackgroundGeolocation#getCurrentPosition` (which always works, even if plugin is `#stop`ped.

Also, Life360 may not yet have released a build targeting Android API 26.

It is possible to have a scheduled-job running which fires every **15 min** on Android without a foreground-service (possibly throttled), but that scheduled-job **will terminate when user terminates app**.  `stopOnTerminate: false` will not help you here.  I plan to eventually implement a scheduled-job in an Android implementation of my [`nativescript-background-fetch`](https://github.com/transistorsoft/nativescript-background-fetch) plugin.  I've been experimenting with Evernote's [`android-job`](https://github.com/evernote/android-job) library.

Welcome to the strict new world of Android 8 Background Execution.

**Comment by ShawnPavel** [comment]
Thank you for the explanation. I appreciate it.
