### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'keys.count')

### ISSUE THREAD

**Issue by randy-johnson** [transistorsoft/nativescript-background-geolocation-lt#91]
## Your Environment
* Plugin version: 1.7.0
* Platform: iOS
* OS version: 10.12.6
* Device manufacturer / model: simulator ios 11 iphone 8+
* Nativescript version (`tns info`): 3.2.1
* Plugin config
```
desiredAccuracy: 0,
            distanceFilter: 50,
            heartbeatInterval: 60*15,
            foregroundService: false,
            url: config.apiUrl+"/location",
            params: {
                        user_id: appSettings.getString("user_id"),
                        user_token: appSettings.getString("user_token"),
                        device_token: "",
                        time_in_sec: Math.floor((new Date()).getTime() / 1000),
                        localtime: dt
            },
            method:"POST",
            autoSync: true,
            startOnBoot:true
```

When I am working on the app, and the app refreshes I will get this error every 2 or 3 app refreshes.

```
5573  : (NativeScript) file:///app/tns_modules/nativescript-background-geolocation-lt/background-geolocation.js:439:39: JS ERROR TypeError: undefined is not an object (evaluating 'keys.count')
```

Any ideas what might be causing this?

**Comment by christocracy** [comment]
Do you have the full stack-trace?  This error is coming from a method which is called by every event.  I need to know which event is fired to cause this error.

**Comment by randy-johnson** [comment]
ok, will provide that tonight.  My apologies on the delay.

**Comment by randy-johnson** [comment]
Whatever was causing this the other night is not happening now.  If it happens again I will update the ticket.
